// GENERATED by scripts/gen_mirrors.py — do not edit by hand.
//
// One shape declaration per public type of `z_core::api`, so that Dart gets a
// real class for each instead of an opaque handle. Without these, the UI could
// not read why a Protect was refused, or which case an outcome is.
//
// Gate G12 regenerates this file and fails the build if it differs.
#![allow(dead_code)]

use flutter_rust_bridge::frb;
// Re-exported: the generated bridge code refers to these by path.
pub use z_core::api::*;

#[frb(mirror(ApiError))]
pub enum _ApiError {
    /// The function exists in the contract but its stage has not been built yet.
    NotImplemented,
    /// No such session, or it was closed.
    InvalidSession,
    /// No such payload.
    InvalidHandle,
    /// The document changed after this payload was built. Build a new one.
    StalePayload { expected: u32, got: u32 },
    /// The vault must be opened before this can be answered.
    VaultLocked,
    /// The chosen provider has no key, or is not reachable.
    ProviderUnavailable { provider: String },
    /// Suggestions are still unanswered; there is no way past them.
    OpenSuggestions { count: u32 },
    /// The file could not be read as text, and why.
    ImportRefused { reason: String },
    /// A span outside the text, reversed, or inside a character.
    BadSpan { reason: String },
    /// No such token in this session.
    UnknownToken,
    /// Nothing is protected and nothing is written; there is nothing to build.
    NothingToSend,
}

#[frb(mirror(SessionId))]
pub struct _SessionId {
    pub id: u32,
}

#[frb(mirror(Revision))]
pub struct _Revision {
    pub n: u32,
}

#[frb(mirror(PayloadHandle))]
pub struct _PayloadHandle {
    pub id: u32,
    pub session: u32,
    pub revision: u32,
}

#[frb(mirror(ProviderId))]
pub struct _ProviderId {
    pub id: String,
}

#[frb(mirror(AnswerId))]
pub struct _AnswerId {
    pub id: u32,
}

#[frb(mirror(Span))]
pub struct _Span {
    pub start: u32,
    pub end: u32,
}

#[frb(mirror(Scope))]
pub enum _Scope {
    /// This place in this document only.
    Once,
    /// Every appearance in this conversation, under one token.
    Conversation,
    /// Kept in the vault and found by itself from now on.
    Always,
}

#[frb(mirror(Kind))]
pub enum _Kind {
    Person,
    Company,
    Email,
    Phone,
    Iban,
    TaxId,
    CustomerNo,
    Address,
    Contract,
    Project,
    Client,
    Custom,
}

#[frb(mirror(Source))]
pub enum _Source {
    /// Shapes that need no language: an IBAN, an e-mail, a postcode.
    GeneralRule,
    /// The habits of one language: Herr, Frau, GmbH, Kundennummer.
    LanguagePack,
    /// Your own people and things.
    Vault,
    /// You selected it.
    Hand,
}

#[frb(mirror(MarkState))]
pub enum _MarkState {
    Protected,
    Suggested,
}

#[frb(mirror(VaultState))]
pub enum _VaultState {
    Locked,
    Unlocked,
}

#[frb(mirror(FindingAnswer))]
pub enum _FindingAnswer {
    Protect,
    Always,
    NotSensitive,
    Skip,
}

#[frb(mirror(Mark))]
pub struct _Mark {
    pub span: Span,
    pub state: MarkState,
    pub token: Option<String>,
    pub kind: Kind,
    pub source: Source,
    /// Pack id, entity id, or the rule's name — the "why" behind the mark.
    pub source_detail: String,
}

#[frb(mirror(DocumentView))]
pub struct _DocumentView {
    pub text: String,
    pub marks: Vec<Mark>,
}

#[frb(mirror(PayloadView))]
pub struct _PayloadView {
    pub text: String,
    pub protected_count: u32,
    pub open_suggestions: u32,
}

#[frb(mirror(TokenRow))]
pub struct _TokenRow {
    pub token: String,
    pub kind: Kind,
    pub scope: Scope,
    pub source: Source,
    pub source_detail: String,
}

#[frb(mirror(RevealedValue))]
pub struct _RevealedValue {
    pub token: String,
    pub value: String,
    pub ttl_ms: u32,
}

#[frb(mirror(Segment))]
pub struct _Segment {
    pub text: String,
    pub restored: bool,
}

#[frb(mirror(LayerCount))]
pub struct _LayerCount {
    pub source: Source,
    pub detail: String,
    pub count: u32,
}

#[frb(mirror(ScanReport))]
pub struct _ScanReport {
    pub auto: u32,
    pub suggested: u32,
    pub normal: u32,
    pub by_layer: Vec<LayerCount>,
}

#[frb(mirror(Finding))]
pub struct _Finding {
    pub id: u32,
    pub span: Span,
    pub kind: Kind,
    pub source: Source,
    pub reason: String,
    pub state: MarkState,
}

#[frb(mirror(ProtectOutcome))]
pub enum _ProtectOutcome {
    /// Protected here, and in `places` places if all matches were taken.
    Applied { token: String, places: u32 },
    /// It was already protected; nothing to do but say by whom.
    AlreadyProtected { token: String, source: Source, source_detail: String },
    /// A new spelling of something known: alias of that identity, or a new one?
    BelongsToEntity { entity: String, token: String },
    /// The selection cut a protected item; these whole items were taken instead.
    Snapped { spans: Vec<Span> },
}

#[frb(mirror(UndoOutcome))]
pub enum _UndoOutcome {
    NothingToUndo,
    /// `created_entity` is set when that act had also added a vault identity.
    Undone { token: String, places: u32, created_entity: Option<String> },
}

#[frb(mirror(SwitchOutcome))]
pub struct _SwitchOutcome {
    pub kept_tokens: u32,
    pub revision: u32,
}

#[frb(mirror(RescanOutcome))]
pub struct _RescanOutcome {
    pub changed_to_manual: u32,
    pub revision: u32,
}

#[frb(mirror(VaultUnlockOutcome))]
pub enum _VaultUnlockOutcome {
    Unlocked { identities: u32, values: u32 },
    WrongPassphrase { attempts_left: u32 },
}

