// GENERATED by scripts/gen_mirrors.py — do not edit by hand.
//
// One shape declaration per public type of `z_core::api`, so that Dart gets a
// real class for each instead of an opaque handle. Without these, the UI could
// not read why a Protect was refused, or which case an outcome is.
//
// Gate G12 regenerates this file and fails the build if it differs.
#![allow(dead_code)]

use flutter_rust_bridge::frb;
// Re-exported: the generated bridge code refers to these by path.
pub use z_core::api::*;

#[frb(mirror(ApiError))]
pub enum _ApiError {
    /// The function exists in the contract but its stage has not been built yet.
    NotImplemented,
    /// No such session, or it was closed.
    InvalidSession,
    /// No such payload.
    InvalidHandle,
    /// The document changed after this payload was built. Build a new one.
    StalePayload { expected: u32, got: u32 },
    /// The vault must be opened before this can be answered.
    VaultLocked,
    /// The chosen provider has no key, or is not reachable.
    ProviderUnavailable { provider: String },
    /// Suggestions are still unanswered; there is no way past them.
    OpenSuggestions { count: u32 },
    /// A folder, a profile or a pack could not be used, and why.
    ImportRefused { reason: String },
    /// A document was not imported, with the named reason and a detail for the
    /// user («page 3 of 20 has no text layer»).
    DocumentRefused { reason: Refusal, detail: String },
    /// A span outside the text, reversed, or inside a character.
    BadSpan { reason: String },
    /// No such token in this session.
    UnknownToken,
    /// Nothing is protected and nothing is written; there is nothing to build.
    NothingToSend,
    /// The built payload failed the core's own leak audit and was thrown away.
    /// This should never reach a user; if it does, the bug stayed inside.
    PayloadRefused { reason: String },
    /// The network did not carry the question, and why. Never a response body:
    /// a provider's error page can quote the request back, so nothing that comes
    /// off the wire is allowed into this message.
    NetworkRefused { reason: NetworkRefusal, detail: String },
}

#[frb(mirror(NetworkRefusal))]
pub enum _NetworkRefusal {
    /// This provider has no credential in this run.
    NotConnected,
    /// The address is not `https`, and is not a machine on this computer.
    InsecureUrl,
    /// The host answered with a redirect. We do not follow one: the safe payload
    /// and the credential were addressed to *this* host and go nowhere else.
    Redirected { status: u32 },
    /// The host answered, but not with an answer.
    BadStatus { status: u32 },
    /// Nothing came back in time.
    Timeout { millis: u32 },
    /// The answer was longer than we accept.
    ResponseTooLarge { limit_kib: u32 },
    /// The outgoing text is longer than this provider accepts. Checked **before**
    /// a socket is opened, so a huge document is refused here rather than turned
    /// into an unreasonable request. (Task 021.)
    PayloadTooLarge { kib: u32, limit_kib: u32 },
    /// The answer arrived but is not the shape this provider promised.
    Unreadable,
    /// The host could not be reached at all.
    Unreachable,
}

#[frb(mirror(SessionId))]
pub struct _SessionId {
    pub id: u32,
}

#[frb(mirror(Revision))]
pub struct _Revision {
    pub n: u32,
}

#[frb(mirror(PayloadHandle))]
pub struct _PayloadHandle {
    pub id: u32,
    pub session: u32,
    pub revision: u32,
}

#[frb(mirror(ProviderId))]
pub struct _ProviderId {
    pub id: String,
}

#[frb(mirror(ProviderRow))]
pub struct _ProviderRow {
    pub id: String,
    pub label: String,
    /// True when a credential for this provider exists in this run.
    pub connected: bool,
    /// True when that credential lives only in memory, because there was no open
    /// vault to seal it into. It is gone when the app closes, and the UI says so
    /// rather than letting the user believe it was saved.
    pub session_only: bool,
    /// Where requests go. Editable, so a local model on this machine can be used.
    pub base_url: String,
    /// Which model is asked. Not a secret, and shown so the answer can be read
    /// knowing what produced it.
    pub model: String,
}

#[frb(mirror(AnswerId))]
pub struct _AnswerId {
    pub id: u32,
}

#[frb(mirror(Span))]
pub struct _Span {
    pub start: u32,
    pub end: u32,
}

#[frb(mirror(Scope))]
pub enum _Scope {
    /// This place in this document only.
    Once,
    /// Every appearance in this conversation, under one token.
    Conversation,
    /// Kept in the vault and found by itself from now on.
    Always,
}

#[frb(mirror(Kind))]
pub enum _Kind {
    Person,
    Company,
    Email,
    Phone,
    /// An IBAN — an account, internationally addressed.
    Iban,
    /// A bank's own identifier (SWIFT/BIC). Not an IBAN, and not the same secret.
    Bic,
    /// A plain account number, as a German letter writes it after «Kontonummer:».
    Account,
    TaxId,
    CustomerNo,
    Address,
    Contract,
    Project,
    Client,
    Custom,
}

#[frb(mirror(Source))]
pub enum _Source {
    /// Shapes that need no language: an IBAN, an e-mail, a postcode.
    GeneralRule,
    /// The habits of one language: Herr, Frau, GmbH, Kundennummer.
    LanguagePack,
    /// Your own people and things.
    Vault,
    /// You selected it.
    Hand,
}

#[frb(mirror(MarkState))]
pub enum _MarkState {
    Protected,
    Suggested,
}

#[frb(mirror(VaultState))]
pub enum _VaultState {
    /// There is no vault on this device yet.
    Absent,
    /// It exists and is sealed. The vault layer is skipped entirely while it is.
    Locked,
    Unlocked,
}

#[frb(mirror(DocumentKind))]
pub enum _DocumentKind {
    Txt,
    Docx,
    Pdf,
}

#[frb(mirror(Refusal))]
pub enum _Refusal {
    /// Pages with no text layer at all — a photograph of a document. We do not
    /// guess, and we do not send it anywhere to be read.
    ScannedPdfNoTextLayer { pages: u32 },
    /// The file is encrypted. Opening it would need its password, which is a
    /// different conversation.
    EncryptedPdf,
    /// The text is there but this build cannot read it faithfully.
    ///
    /// `page` names where (0 for the file as a whole) and `readable_percent` says
    /// how much of that page came out as text. **Measured per page on purpose:**
    /// nineteen clean pages and one at 41% average out to «fine», and the page
    /// that failed is exactly the page with the client's name on it.
    UnsupportedEncoding { page: u32, readable_percent: u32 },
    /// The page's fonts or filters are ones this reader does not understand, so
    /// nothing on it can be trusted — refused even if part of it looks like words.
    /// Fail-closed: the dangerous failure is not a refused import, it is an import
    /// that looks successful while secrets sit in text we could not see.
    UnreadableStructure { page: u32 },
    /// The file does not hold together: a broken zip, a truncated PDF.
    MalformedDocument,
    /// Bigger than the limit. A document is untrusted input; one file may not eat
    /// the machine.
    DocumentTooLarge { mib: u32, limit_mib: u32 },
    /// More pages than the limit.
    TooManyPages { pages: u32, limit: u32 },
    /// The text after decompression is past the limit — a small file that swells.
    TextTooLarge { limit_mib: u32 },
    /// A few compressed bytes that unpack into a great many: a zip bomb.
    CompressionBomb { ratio: u32 },
    /// More parts inside the file than a document has any reason to hold.
    TooManyParts { parts: u32, limit: u32 },
    /// Reading it took longer than the limit.
    TookTooLong { millis: u32 },
    /// Empty, or nothing but whitespace: there is nothing to protect.
    EmptyDocument,
}

#[frb(mirror(Place))]
pub struct _Place {
    pub page: u32,
    pub paragraph: u32,
}

#[frb(mirror(EntityKind))]
pub enum _EntityKind {
    Client,
    Person,
    Company,
    Project,
    Custom,
}

#[frb(mirror(Policy))]
pub enum _Policy {
    /// Replaced the moment it appears.
    Always,
    /// Marked and counted, waiting for your word.
    Suggest,
    /// Never found by itself; kept here so its aliases and token stay stable.
    Manual,
}

#[frb(mirror(EntityRow))]
pub struct _EntityRow {
    pub id: u32,
    pub kind: EntityKind,
    pub label: String,
    pub profile_id: Option<String>,
    pub values: u32,
    /// «4 always · 1 suggest», as the vault list shows it.
    pub policy_summary: String,
}

#[frb(mirror(ValueRow))]
pub struct _ValueRow {
    pub id: u32,
    pub kind: Kind,
    pub aliases: u32,
    pub policy: Policy,
}

#[frb(mirror(EntityCard))]
pub struct _EntityCard {
    pub id: u32,
    pub kind: EntityKind,
    pub label: String,
    pub profile_id: Option<String>,
    pub values: Vec<ValueRow>,
}

#[frb(mirror(FindingAnswer))]
pub enum _FindingAnswer {
    Protect,
    Always,
    NotSensitive,
    Skip,
}

#[frb(mirror(Mark))]
pub struct _Mark {
    pub span: Span,
    pub state: MarkState,
    pub token: Option<String>,
    pub kind: Kind,
    pub source: Source,
    /// Pack id, entity id, or the rule's name — the "why" behind the mark.
    pub source_detail: String,
    /// The page and paragraph it sits on, when the text came from a document.
    pub place: Option<Place>,
}

#[frb(mirror(DocumentView))]
pub struct _DocumentView {
    pub text: String,
    pub marks: Vec<Mark>,
    /// What the user called it: a file name, or empty for text typed in.
    pub name: String,
    pub kind: DocumentKind,
    pub pages: u32,
}

#[frb(mirror(PayloadView))]
pub struct _PayloadView {
    pub text: String,
    pub protected_count: u32,
    pub open_suggestions: u32,
}

#[frb(mirror(TokenRow))]
pub struct _TokenRow {
    pub token: String,
    pub kind: Kind,
    pub scope: Scope,
    pub source: Source,
    pub source_detail: String,
}

#[frb(mirror(RevealedValue))]
pub struct _RevealedValue {
    pub token: String,
    pub value: String,
    pub ttl_ms: u32,
}

#[frb(mirror(Segment))]
pub struct _Segment {
    pub text: String,
    pub restored: bool,
}

#[frb(mirror(LayerCount))]
pub struct _LayerCount {
    pub source: Source,
    pub detail: String,
    pub count: u32,
}

#[frb(mirror(ScanReport))]
pub struct _ScanReport {
    pub auto: u32,
    pub suggested: u32,
    pub normal: u32,
    pub by_layer: Vec<LayerCount>,
    /// Said out loud, because a locked vault means the app cannot recognise your
    /// own people: the general rules and the pack still run, the vault layer does
    /// not, and the band under the header says so.
    pub vault: VaultState,
}

#[frb(mirror(Finding))]
pub struct _Finding {
    pub id: u32,
    pub span: Span,
    pub kind: Kind,
    pub source: Source,
    pub reason: String,
    pub state: MarkState,
    /// The vault identities that claim this text.
    ///
    /// Empty when no identity is involved; one when the vault knows it; **more
    /// than one is a conflict** — two identities claim the same spelling, and the
    /// scanner refuses to choose silently. The app must ask.
    pub entities: Vec<String>,
    /// Where it sits: page and paragraph. Kept through protection, so a review
    /// list can still jump to page 17 after everything is replaced.
    pub place: Option<Place>,
}

#[frb(mirror(ProtectOutcome))]
pub enum _ProtectOutcome {
    /// Protected here, and in `places` places if all matches were taken.
    Applied { token: String, places: u32 },
    /// It was already protected; nothing to do but say by whom.
    AlreadyProtected { token: String, source: Source, source_detail: String },
    /// A new spelling of something known: alias of that identity, or a new one?
    BelongsToEntity { entity: String, token: String },
    /// The selection cut a protected item; these whole items were taken instead.
    Snapped { spans: Vec<Span> },
}

#[frb(mirror(UndoOutcome))]
pub enum _UndoOutcome {
    NothingToUndo,
    /// `created_entity` is set when that act had also added a vault identity.
    Undone { token: String, places: u32, created_entity: Option<String> },
}

#[frb(mirror(SwitchOutcome))]
pub struct _SwitchOutcome {
    pub kept_tokens: u32,
    pub revision: u32,
}

#[frb(mirror(RescanOutcome))]
pub struct _RescanOutcome {
    pub changed_to_manual: u32,
    pub revision: u32,
}

#[frb(mirror(VaultUnlockOutcome))]
pub enum _VaultUnlockOutcome {
    Unlocked { identities: u32, values: u32 },
    WrongPassphrase { attempts_left: u32 },
}

