// GENERATED by scripts/gen_mirrors.py — do not edit by hand.
//
// One shape declaration per public type of `z_core::api`, so that Dart gets a
// real class for each instead of an opaque handle. Without these, the UI could
// not read why a Protect was refused, or which case an outcome is.
//
// Gate G12 regenerates this file and fails the build if it differs.
#![allow(dead_code)]

use flutter_rust_bridge::frb;
// Re-exported: the generated bridge code refers to these by path.
pub use z_core::api::*;

#[frb(mirror(ApiError))]
pub enum _ApiError {
    /// The function exists in the contract but its stage has not been built yet.
    NotImplemented,
    /// No such session, or it was closed.
    InvalidSession,
    /// No such payload.
    InvalidHandle,
    /// The document changed after this payload was built. Build a new one.
    StalePayload { expected: u32, got: u32 },
    /// The vault must be opened before this can be answered.
    VaultLocked,
    /// The chosen provider has no key, or is not reachable.
    ProviderUnavailable { provider: String },
    /// Suggestions are still unanswered; there is no way past them.
    OpenSuggestions { count: u32 },
    /// What was given cannot be used, and why: an empty value, a name left
    /// blank, a passphrase too short, a credential missing where one is
    /// needed, a scope that does not apply in this conversation.
    ///
    /// The person's next move is to change what they entered.
    InputRefused { reason: String },
    /// Something was named that is not here — a profile, a rule set, a pack, a
    /// taught rule. `UnknownToken` is this same shape for a token in a session.
    ///
    /// The person's next move is to name something else.
    NotFound { reason: String },
    /// There is no vault on this device yet, so there is nothing to open, to
    /// change, or to keep anything in.
    ///
    /// Three neighbours, deliberately apart: this one means **there is none**,
    /// `VaultLocked` means there is one and it is shut, and `VaultRequired`
    /// means an act needs one open and none is.
    VaultAbsent,
    /// A vault is already on this device, and making another would write over
    /// it. Refused rather than merged: there is no way back from that.
    VaultAlreadyExists,
    /// A place Z Privacy keeps its **own** files cannot be used safely — a
    /// symlink where a directory belongs, permissions that let someone else
    /// read it, a temporary file left by another program.
    ///
    /// Nothing the person typed is wrong here, so it is not `InputRefused`.
    StorageRefused { reason: String },
    /// A document was not imported, with the named reason and a detail for the
    /// user («page 3 of 20 has no text layer»).
    DocumentRefused { reason: Refusal, detail: String },
    /// A span outside the text, reversed, or inside a character.
    BadSpan { reason: String },
    /// No such token in this session.
    UnknownToken,
    /// Nothing is protected and nothing is written; there is nothing to build.
    NothingToSend,
    /// The built payload failed the core's own leak audit and was thrown away.
    /// This should never reach a user; if it does, the bug stayed inside.
    PayloadRefused { reason: String },
    /// The network did not carry the question, and why. Never a response body:
    /// a provider's error page can quote the request back, so nothing that comes
    /// off the wire is allowed into this message.
    NetworkRefused { reason: NetworkRefusal, detail: String },
    /// A vault file asked for KDF costs this build does not support.
    UnsupportedKdfParameters { reason: String },
    /// A vault file had bytes after the end of the versioned ZVLT structure.
    TrailingVaultData,
    /// The vault could not be authenticated after key derivation.
    ///
    /// This does not distinguish a wrong passphrase from a modified vault: the
    /// AEAD tag proves only that opening failed, not which human story caused it.
    VaultAuthenticationFailed,
    /// This payload handle already drove a send, or is driving one now.
    PayloadAlreadySent,
    /// The act needs an open vault — Always, Profile, or anything kept for tomorrow —
    /// and there is not one. Named so a press that cannot keep its promise cannot
    /// look like success.
    VaultRequired,
}

#[frb(mirror(NetworkRefusal))]
pub enum _NetworkRefusal {
    /// This provider has no credential in this run.
    NotConnected,
    /// The address is not `https`, and is not a machine on this computer.
    InsecureUrl,
    /// The host answered with a redirect. We do not follow one: the safe payload
    /// and the credential were addressed to *this* host and go nowhere else.
    Redirected { status: u32 },
    /// The host answered, but not with an answer.
    BadStatus { status: u32 },
    /// Nothing came back in time.
    Timeout { millis: u32 },
    /// The answer was longer than we accept.
    ResponseTooLarge { limit_kib: u32 },
    /// The outgoing text is longer than this provider accepts. Checked **before**
    /// a socket is opened, so a huge document is refused here rather than turned
    /// into an unreasonable request. (Task 021.)
    PayloadTooLarge { kib: u32, limit_kib: u32 },
    /// The answer arrived but is not the shape this provider promised.
    Unreadable,
    /// The host could not be reached at all.
    Unreachable,
}

#[frb(mirror(SessionId))]
pub struct _SessionId {
    pub id: u32,
}

#[frb(mirror(Revision))]
pub struct _Revision {
    pub n: u32,
}

#[frb(mirror(PayloadHandle))]
pub struct _PayloadHandle {
    pub id: u32,
    pub session: u32,
    pub revision: u32,
}

#[frb(mirror(ProviderId))]
pub struct _ProviderId {
    pub id: String,
}

#[frb(mirror(Explanation))]
pub struct _Explanation {
    /// «You taught this value» · «German privacy rule» · «You protected this
    /// by hand» · «A shape that needs no language».
    pub headline: String,
    /// The particulars, one per line: «Valid IBAN checksum», «German label:
    /// Mobil», «Two rules agree». Empty is not allowed to happen — a protection
    /// with nothing to say about itself is the black box arriving.
    pub because: Vec<String>,
    pub kind: Kind,
    pub scope: Scope,
    /// Where it applies: «This document only» · «Client Nordstern» · «Everywhere».
    pub applies: String,
    /// Whether a person decided this, or a layer did.
    pub decided: bool,
    pub token: String,
    /// When it was taught, in seconds since 1970. 0 when it was not taught at
    /// all (a rule found it) or when the vault predates the date being kept.
    pub learned_at: u64,
    /// The identity and value it came from, when the vault taught it. This is
    /// what «Edit» and «Forget» act on.
    pub entity: Option<u32>,
    pub value_id: Option<u32>,
    /// Other spellings of the same value. Shown behind one tap, like every
    /// other value in this app.
    pub aliases: Vec<String>,
    /// The reach of the taught value, when one was taught — so the «Forget»
    /// button can carry its own scope in its name instead of leaving a person
    /// to assemble the meaning from a line of small print. `None` when nothing
    /// was taught, which is the same case as `entity`/`value_id` being `None`.
    pub taught_reach: Option<TaughtReach>,
}

#[frb(mirror(TaughtReach))]
pub enum _TaughtReach {
    /// The identity holding it belongs to one profile.
    ThisProfile,
    /// It belongs to no profile, so every profile knows it.
    Everywhere,
}

#[frb(mirror(ForgetPlan))]
pub struct _ForgetPlan {
    /// What it is, so the sheet can name it back to the user.
    pub what: String,
    pub values: u32,
    pub aliases: u32,
    /// Identities that would be left holding nothing, and so go too.
    pub identities: u32,
    /// The profiles it is associated with, by name.
    pub profiles: Vec<String>,
    /// What is **not** touched, said out loud because the user is about to
    /// press a button that says «forget».
    pub keeps: Vec<String>,
    /// Permanent knowledge that could recognise this value **in future**.
    ///
    /// The definition is strict on purpose (the owner, 28 Sep). Empty means:
    /// *no permanent knowledge **in the current vault** will recognise this
    /// value again.* It is not a claim about every copy of the vault that has
    /// ever existed: an older valid one may be restored and bring the value
    /// back, which is F-02 and is stated as an accepted limitation rather than
    /// quietly contradicted here. It does
    /// **not** mean the value is nowhere in the program — the open
    /// conversation's token store still holds it, and an answer already
    /// received still reads as it did. Those are not knowledge for tomorrow;
    /// they are today's work, and `keeps` says so in words.
    ///
    /// Must be empty after forgetting. Reported rather than assumed, and both a
    /// test and the screen check it.
    pub still_known_by: Vec<String>,
}

#[frb(mirror(SelectionView))]
pub struct _SelectionView {
    /// Empty when the span holds nothing but space.
    pub empty: bool,
    /// The pack's guess. `Custom` when nothing recognised it.
    pub kind: Kind,
    /// How many places this exact value stands in this document, protected or
    /// not. 1 means «all matches» is the same act as «protect», and the button
    /// hides its count.
    pub matches: u32,
    /// The token, when this exact stretch is already protected. Then the only
    /// act offered is Undo.
    pub protected_as: Option<String>,
    pub protected_by: Option<Source>,
    /// «Z Vault · CLIENT #17», «de:salutation», «selected by you» — the why.
    pub protected_detail: String,
    /// The identity the vault knows this value under, when it knows one. Two or
    /// more is a conflict the app must put to the user, never settle itself.
    pub entities: Vec<String>,
    /// The whole protected items this selection cuts into. Non-empty means
    /// Protect would snap to these instead of taking the selection as drawn.
    pub snaps_to: Vec<Span>,
}

#[frb(mirror(Settings))]
pub struct _Settings {
    /// Scan the moment a document arrives, with no dialog. On by default: the
    /// boards' rule is that nobody has to press anything to be protected.
    pub scan_on_import: bool,
    /// How long a revealed value stays on screen.
    pub reveal_seconds: u32,
    /// Lock the vault after this many minutes of not being used. 0 = never.
    /// Enforced **in the core**, not by a timer in the UI: a screen that forgot
    /// to count would leave the vault open, and nobody would know.
    pub auto_lock_minutes: u32,
    /// The detection pack a new session starts with.
    pub pack_id: String,
    /// The working language, `en` or `de`.
    ///
    /// **What it selects in v1, exactly:** the language of the First Run page,
    /// and the rule set a new session starts with. It does **not** translate
    /// the interface, which is English. The field is named `ui_language` in the
    /// settings file; that name describes what it will govern, not all it
    /// governs today, and the First Run page says so out loud rather than
    /// letting a person infer a translated app from choosing «Deutsch».
    ///
    /// It is also not «the rule set»: more than one set can run in a scan
    /// (M7.10A), so this picks a starting point, not the only engine allowed.
    pub language: String,
    /// False until the first-run page has been passed.
    pub first_run_done: bool,
    /// True when all of the above will be gone when the app closes, because
    /// there is no vault to keep them in.
    pub session_only: bool,
}

#[frb(mirror(KindRow))]
pub struct _KindRow {
    pub kind: Kind,
    /// What to call it. The core's word, not the screen's.
    pub label: String,
    /// True for a kind the user made. Always false today; the field exists so
    /// that the day it is true, nothing above it needs rewriting.
    pub custom: bool,
}

#[frb(mirror(ProfileRow))]
pub struct _ProfileRow {
    pub id: String,
    pub name: String,
    /// The rule sets switched on for this client's documents. A firm that works
    /// in two languages runs both **in one scan**, so this is a list.
    pub languages: Vec<String>,
}

#[frb(mirror(RuleSetRow))]
pub struct _RuleSetRow {
    pub id: String,
    pub label: String,
    /// How many label rules it carries. Counted, never written down — a number
    /// on a screen must have a source (§2 of the invariants).
    pub rules: u32,
}

#[frb(mirror(LabelRuleRow))]
pub struct _LabelRuleRow {
    pub id: u32,
    /// The word as they typed it.
    pub label: String,
    pub kind: Kind,
    /// `None` is everywhere; `Some` names the profile it belongs to.
    pub profile_id: Option<String>,
    pub profile_name: Option<String>,
    /// Days since the epoch, 0 when unknown — never today's date guessed in.
    pub learned_at: u64,
}

#[frb(mirror(PackRow))]
pub struct _PackRow {
    pub id: String,
    pub label: String,
}

#[frb(mirror(ProviderRow))]
pub struct _ProviderRow {
    pub id: String,
    pub label: String,
    /// True when this provider can be used at this address in this run.
    pub connected: bool,
    /// True when that usable connection lives only in memory, because there was
    /// no open vault to seal it into. It is gone when the app closes, and the UI
    /// says so rather than letting the user believe it was saved.
    pub session_only: bool,
    /// Where requests go. Editable, so a local model on this machine can be used.
    pub base_url: String,
    /// Which model is asked. Not a secret, and shown so the answer can be read
    /// knowing what produced it.
    pub model: String,
    /// Whether this provider, **at this address**, needs a credential at all.
    ///
    /// A property of the provider, not a rule of the world (the owner, 27 Sep):
    /// a model on this machine needs none, and a future provider may authorise
    /// some other way. A screen asks this instead of assuming.
    pub credential_required: bool,
}

#[frb(mirror(CredentialState))]
pub enum _CredentialState {
    /// No credential is stored for this provider, in the vault or in memory.
    Missing,
    /// Kept in process memory for this run only.
    SessionOnly,
    /// Sealed inside the vault.
    EncryptedInVault,
}

#[frb(mirror(ScanOrigin))]
pub enum _ScanOrigin {
    NotScanned,
    OnImport,
    Rescan,
}

#[frb(mirror(AnswerId))]
pub struct _AnswerId {
    pub id: u32,
}

#[frb(mirror(Span))]
pub struct _Span {
    pub start: u32,
    pub end: u32,
}

#[frb(mirror(Scope))]
pub enum _Scope {
    /// This one place, and nothing else.
    Once,
    /// Every appearance in this conversation, under one token. Gone when the
    /// conversation is.
    Conversation,
    /// Every appearance here, **and kept in the vault under the profile this
    /// conversation is in** — so it is found by itself in that client's next
    /// document, and in no other client's.
    ///
    /// The level a firm with several clients needs: what you learn about one of
    /// them does not become a rule about all of them.
    Profile,
    /// Every appearance here, and kept in the vault for **every** profile.
    Always,
}

#[frb(mirror(Kind))]
pub enum _Kind {
    Person,
    Company,
    Email,
    Phone,
    /// An IBAN — an account, internationally addressed.
    Iban,
    /// A bank's own identifier (SWIFT/BIC). Not an IBAN, and not the same secret.
    Bic,
    /// A plain account number, as a German letter writes it after «Kontonummer:».
    Account,
    TaxId,
    CustomerNo,
    Address,
    Contract,
    Project,
    Client,
    /// A national identity card number — `Personalausweisnummer L01X00T47`.
    IdCard,
    /// A date of birth. The date alone: «geboren am» stays in the clear, as a
    /// salutation does, so the sentence still reads.
    Birthdate,
    /// A vehicle's registration plate.
    Vehicle,
    Custom,
}

#[frb(mirror(Source))]
pub enum _Source {
    /// Shapes that need no language: an IBAN, an e-mail, a postcode.
    GeneralRule,
    /// The habits of one language: Herr, Frau, GmbH, Kundennummer.
    LanguagePack,
    /// Your own people and things.
    Vault,
    /// You selected it.
    Hand,
}

#[frb(mirror(MarkState))]
pub enum _MarkState {
    Protected,
    Suggested,
}

#[frb(mirror(VaultState))]
pub enum _VaultState {
    /// There is no vault on this device yet.
    Absent,
    /// It exists and is sealed. The vault layer is skipped entirely while it is.
    Locked,
    Unlocked,
}

#[frb(mirror(DocumentKind))]
pub enum _DocumentKind {
    Txt,
    Docx,
    Pdf,
}

#[frb(mirror(Refusal))]
pub enum _Refusal {
    /// Pages with no text layer at all — a photograph of a document. We do not
    /// guess, and we do not send it anywhere to be read.
    ScannedPdfNoTextLayer { pages: u32 },
    /// The file is encrypted. Opening it would need its password, which is a
    /// different conversation.
    EncryptedPdf,
    /// The text is there but this build cannot read it faithfully.
    ///
    /// `page` names where (0 for the file as a whole) and `readable_percent` says
    /// how much of that page came out as text. **Measured per page on purpose:**
    /// nineteen clean pages and one at 41% average out to «fine», and the page
    /// that failed is exactly the page with the client's name on it.
    UnsupportedEncoding { page: u32, readable_percent: u32 },
    /// The page's fonts or filters are ones this reader does not understand, so
    /// nothing on it can be trusted — refused even if part of it looks like words.
    /// Fail-closed: the dangerous failure is not a refused import, it is an import
    /// that looks successful while secrets sit in text we could not see.
    UnreadableStructure { page: u32 },
    /// The file does not hold together: a broken zip, a truncated PDF.
    MalformedDocument,
    /// Bigger than the limit. A document is untrusted input; one file may not eat
    /// the machine.
    DocumentTooLarge { mib: u32, limit_mib: u32 },
    /// More pages than the limit.
    TooManyPages { pages: u32, limit: u32 },
    /// The text after decompression is past the limit — a small file that swells.
    TextTooLarge { limit_mib: u32 },
    /// A few compressed bytes that unpack into a great many: a zip bomb.
    CompressionBomb { ratio: u32 },
    /// More parts inside the file than a document has any reason to hold.
    TooManyParts { parts: u32, limit: u32 },
    /// Reading it took longer than the limit.
    TookTooLong { millis: u32 },
    /// Empty, or nothing but whitespace: there is nothing to protect.
    EmptyDocument,
}

#[frb(mirror(ReportSubject))]
pub enum _ReportSubject {
    /// A document that was imported. Every number comes from the core's own
    /// state; the screen passes nothing but the session.
    Imported { session: SessionId },
    /// A file that was not imported. The screen knows these three things and
    /// the core knows nothing about it at all.
    Refused {
        name: String,
        bytes: u32,
        refusal: Refusal,
    },
}

#[frb(mirror(Place))]
pub struct _Place {
    pub page: u32,
    pub paragraph: u32,
}

#[frb(mirror(EntityKind))]
pub enum _EntityKind {
    Client,
    Person,
    Company,
    Project,
    Custom,
}

#[frb(mirror(Policy))]
pub enum _Policy {
    /// Replaced the moment it appears.
    Always,
    /// Marked and counted, waiting for your word.
    Suggest,
    /// Never found by itself; kept here so its aliases and token stay stable.
    Manual,
}

#[frb(mirror(EntityRow))]
pub struct _EntityRow {
    pub id: u32,
    pub kind: EntityKind,
    pub label: String,
    pub profile_id: Option<String>,
    pub values: u32,
    /// «4 always · 1 suggest», as the vault list shows it.
    pub policy_summary: String,
}

#[frb(mirror(ValueRow))]
pub struct _ValueRow {
    pub id: u32,
    pub kind: Kind,
    pub aliases: u32,
    pub policy: Policy,
}

#[frb(mirror(EntityCard))]
pub struct _EntityCard {
    pub id: u32,
    pub kind: EntityKind,
    pub label: String,
    pub profile_id: Option<String>,
    pub values: Vec<ValueRow>,
}

#[frb(mirror(FindingAnswer))]
pub enum _FindingAnswer {
    Protect,
    Always,
    NotSensitive,
    Skip,
}

#[frb(mirror(Mark))]
pub struct _Mark {
    pub span: Span,
    pub state: MarkState,
    pub token: Option<String>,
    pub kind: Kind,
    /// Who **found** it.
    pub source: Source,
    /// Whether a person **decided** it, as against a layer deciding on its own.
    ///
    /// Two different questions, and mixing them wrote a false history: the pack
    /// may have found a name while you chose to protect it, and a list that
    /// said «you found this» would be wrong. It is also a rule and not only a
    /// label — see [`Scope`] and the rescan behaviour. (Task 033/034.)
    pub decided: bool,
    /// Pack id, entity id, or the rule's name — the "why" behind the mark.
    pub source_detail: String,
    /// The page and paragraph it sits on, when the text came from a document.
    pub place: Option<Place>,
}

#[frb(mirror(DocumentView))]
pub struct _DocumentView {
    pub text: String,
    pub marks: Vec<Mark>,
    /// What the user called it: a file name, or empty for text typed in.
    pub name: String,
    pub kind: DocumentKind,
    pub pages: u32,
}

#[frb(mirror(PayloadView))]
pub struct _PayloadView {
    pub text: String,
    pub protected_count: u32,
    pub open_suggestions: u32,
}

#[frb(mirror(TokenRow))]
pub struct _TokenRow {
    pub token: String,
    pub kind: Kind,
    pub scope: Scope,
    pub source: Source,
    pub decided: bool,
    pub source_detail: String,
}

#[frb(mirror(RevealedToken))]
pub struct _RevealedToken {
    pub token: String,
    pub remaining_ms: u32,
}

#[frb(mirror(RevealedValue))]
pub struct _RevealedValue {
    pub token: String,
    pub value: String,
    /// Every other spelling of the same value. Shown with it because they are
    /// the same secret: a vault screen that listed a name but hid «Herr Müller»
    /// would be keeping something from its owner for no reason.
    pub aliases: Vec<String>,
    pub ttl_ms: u32,
}

#[frb(mirror(Segment))]
pub struct _Segment {
    pub text: String,
    pub restored: bool,
}

#[frb(mirror(LayerCount))]
pub struct _LayerCount {
    pub source: Source,
    pub detail: String,
    pub count: u32,
}

#[frb(mirror(ScanReport))]
pub struct _ScanReport {
    pub auto: u32,
    pub suggested: u32,
    pub normal: u32,
    pub by_layer: Vec<LayerCount>,
    /// Said out loud, because a locked vault means the app cannot recognise your
    /// own people: the general rules and the pack still run, the vault layer does
    /// not, and the band under the header says so.
    pub vault: VaultState,
}

#[frb(mirror(Finding))]
pub struct _Finding {
    pub id: u32,
    pub span: Span,
    pub kind: Kind,
    /// Who found it.
    pub source: Source,
    /// Whether a person decided it. The review list groups by this, not by
    /// `source`: confirming the pack's suggestion is **your** decision.
    pub decided: bool,
    pub reason: String,
    pub state: MarkState,
    /// The vault identities that claim this text.
    ///
    /// Empty when no identity is involved; one when the vault knows it; **more
    /// than one is a conflict** — two identities claim the same spelling, and the
    /// scanner refuses to choose silently. The app must ask.
    pub entities: Vec<String>,
    /// Where it sits: page and paragraph. Kept through protection, so a review
    /// list can still jump to page 17 after everything is replaced.
    pub place: Option<Place>,
}

#[frb(mirror(ProtectOutcome))]
pub enum _ProtectOutcome {
    /// Protected here, and in `places` places if all matches were taken.
    Applied { token: String, places: u32 },
    /// It was already protected; nothing to do but say by whom.
    AlreadyProtected { token: String, source: Source, source_detail: String },
    /// A new spelling of something known: alias of that identity, or a new one?
    BelongsToEntity { entity: String, token: String },
    /// The selection cut a protected item; these whole items were taken instead.
    Snapped { spans: Vec<Span> },
}

#[frb(mirror(UndoOutcome))]
pub enum _UndoOutcome {
    NothingToUndo,
    /// `created_entity` is set when that act had also added a vault identity.
    Undone { token: String, places: u32, created_entity: Option<String> },
}

#[frb(mirror(SwitchOutcome))]
pub struct _SwitchOutcome {
    pub kept_tokens: u32,
    pub revision: u32,
}

#[frb(mirror(RescanOutcome))]
pub struct _RescanOutcome {
    pub changed_to_manual: u32,
    pub revision: u32,
}

#[frb(mirror(VaultUnlockOutcome))]
pub enum _VaultUnlockOutcome {
    Unlocked { identities: u32, values: u32 },
}

#[frb(mirror(HomeSnapshot))]
pub struct _HomeSnapshot {
    pub state_revision: u32,
    pub vault: VaultState,
    pub identity_count: u32,
    pub value_count: u32,
    pub profiles: Vec<ProfileRow>,
    pub packs: Vec<PackRow>,
    pub providers: Vec<ProviderFact>,
    pub settings: Settings,
    pub kinds: Vec<KindRow>,
}

#[frb(mirror(WorkspaceSnapshot))]
pub struct _WorkspaceSnapshot {
    pub state_revision: u32,
    pub session: SessionId,
    pub profile_id: Option<String>,
    pub revision: u32,
    pub scan_origin: ScanOrigin,
    pub auto_protected: u32,
    pub user_protected: u32,
    pub open_suggestions: u32,
    pub normal: u32,
    pub token_count: u32,
    pub can_undo: bool,
    pub findings: Vec<Finding>,
    pub document: DocumentView,
    pub tokens: Vec<TokenRow>,
    pub payload: Option<PayloadView>,
    pub handle: Option<PayloadHandle>,
    pub vault: VaultState,
    pub answers: Vec<AnswerId>,
}

#[frb(mirror(VaultSnapshot))]
pub struct _VaultSnapshot {
    pub state_revision: u32,
    pub vault: VaultState,
    pub identity_count: u32,
    pub value_count: u32,
    pub profiles: Vec<ProfileRow>,
    pub taught_values: Vec<TaughtValueRow>,
    pub can_forget: bool,
}

#[frb(mirror(KnowledgeSource))]
pub enum _KnowledgeSource {
    BuiltIn,
    UserTaughtValue,
    UserException,
}

#[frb(mirror(PrivacyRulesSnapshot))]
pub struct _PrivacyRulesSnapshot {
    pub state_revision: u32,
    pub profile_id: Option<String>,
    pub values: Vec<TaughtValueRow>,
    pub exceptions: Vec<TaughtExceptionRow>,
    /// The label rules this person taught, effective for `profile_id`.
    pub label_rules: Vec<LabelRuleRow>,
    /// Every rule set this build carries, so the screen can offer them without
    /// keeping a list of its own.
    pub rule_sets: Vec<RuleSetRow>,
    /// The sets actually switched on for `profile_id` — what *ran*, not what
    /// was asked for.
    pub active_sets: Vec<String>,
    /// Was the «Rules I taught» section built? True since M7.10B; kept as a
    /// field because a screen must read this, never assume it.
    pub rules_built: bool,
}

#[frb(mirror(TaughtValueRow))]
pub struct _TaughtValueRow {
    pub entity_id: u32,
    pub entity_label: String,
    pub value_id: u32,
    pub kind: Kind,
    pub profile_id: Option<String>,
    pub profile_name: Option<String>,
    /// How many spellings, not which ones — the same shape as `ValueRow`.
    pub aliases: u32,
    pub taught_at: u64,
    pub why: String,
    pub source: KnowledgeSource,
}

#[frb(mirror(TaughtExceptionRow))]
pub struct _TaughtExceptionRow {
    pub id: u32,
    pub value: String,
    pub kind: Kind,
    pub profile_id: Option<String>,
    pub profile_name: Option<String>,
    pub taught_at: u64,
    pub why: String,
    pub source: KnowledgeSource,
}

#[frb(mirror(ProviderSnapshot))]
pub struct _ProviderSnapshot {
    pub state_revision: u32,
    pub providers: Vec<ProviderFact>,
}

#[frb(mirror(ProviderFact))]
pub struct _ProviderFact {
    pub id: String,
    /// What Z Privacy speaks, not what a person chose: «OpenAI-compatible».
    /// A **protocol**, shown where the technical detail belongs.
    pub label: String,
    /// A credential is stored for this provider — not «this provider is set
    /// up». A model on this machine is connected and holds no credential, so
    /// this is `false` while `connected` is `true`, and the two words are not
    /// interchangeable anywhere.
    pub configured: bool,
    pub connected: bool,
    pub endpoint: String,
    pub model: String,
    pub credential_required: bool,
    pub credential_state: CredentialState,
    /// Is this endpoint on this computer?
    ///
    /// Reported by the core from the address itself, never worked out by a
    /// screen — because the word «Local» is a promise about where the text
    /// goes, and a promise must be checked by whoever knows. It is the same
    /// test the network door enforces, so the word and the rule cannot part.
    pub on_this_computer: bool,
}

#[frb(mirror(AnswerSnapshot))]
pub struct _AnswerSnapshot {
    pub state_revision: u32,
    pub answer: AnswerId,
    pub index: u32,
    pub total: u32,
    /// The answer before this one, or `None` at the first.
    ///
    /// Carried here rather than worked out by a screen, for the reason the
    /// whole snapshot exists: `index`/`total` and «which answer do I move to»
    /// must be **one** fact. A list held in Dart alongside a count from Rust
    /// is two sources that will disagree, and «Answer 2 of 2» with a stale
    /// neighbour is the same family as every lie this project has hunted.
    pub previous: Option<AnswerId>,
    /// The answer after this one, or `None` at the last.
    pub next: Option<AnswerId>,
    pub restored: Vec<Segment>,
    pub as_written: String,
}

#[frb(mirror(RevealState))]
pub struct _RevealState {
    pub entity: Option<u32>,
    pub value_id: Option<u32>,
    pub remaining_ms: u32,
}

