[workspace]
resolver = "2"
members = ["z_core", "bridges/native/z_bridge"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "UNLICENSED"

[workspace.lints.rust]
unsafe_code = "forbid"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
missing_debug_implementations = "warn"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
indexing_slicing = "warn"
