// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/core.dart';
import 'api/mirrors.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'third_party/z_core/api.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnswerId dco_decode_answer_id(dynamic raw);

  @protected
  AnswerSnapshot dco_decode_answer_snapshot(dynamic raw);

  @protected
  ApiError dco_decode_api_error(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AnswerId dco_decode_box_autoadd_answer_id(dynamic raw);

  @protected
  NetworkRefusal dco_decode_box_autoadd_network_refusal(dynamic raw);

  @protected
  PayloadHandle dco_decode_box_autoadd_payload_handle(dynamic raw);

  @protected
  PayloadView dco_decode_box_autoadd_payload_view(dynamic raw);

  @protected
  Place dco_decode_box_autoadd_place(dynamic raw);

  @protected
  ProviderId dco_decode_box_autoadd_provider_id(dynamic raw);

  @protected
  Refusal dco_decode_box_autoadd_refusal(dynamic raw);

  @protected
  ReportSubject dco_decode_box_autoadd_report_subject(dynamic raw);

  @protected
  SessionId dco_decode_box_autoadd_session_id(dynamic raw);

  @protected
  Settings dco_decode_box_autoadd_settings(dynamic raw);

  @protected
  Source dco_decode_box_autoadd_source(dynamic raw);

  @protected
  Span dco_decode_box_autoadd_span(dynamic raw);

  @protected
  TaughtReach dco_decode_box_autoadd_taught_reach(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CredentialState dco_decode_credential_state(dynamic raw);

  @protected
  DocumentKind dco_decode_document_kind(dynamic raw);

  @protected
  DocumentView dco_decode_document_view(dynamic raw);

  @protected
  EntityCard dco_decode_entity_card(dynamic raw);

  @protected
  EntityKind dco_decode_entity_kind(dynamic raw);

  @protected
  EntityRow dco_decode_entity_row(dynamic raw);

  @protected
  Explanation dco_decode_explanation(dynamic raw);

  @protected
  Finding dco_decode_finding(dynamic raw);

  @protected
  FindingAnswer dco_decode_finding_answer(dynamic raw);

  @protected
  ForgetPlan dco_decode_forget_plan(dynamic raw);

  @protected
  HomeSnapshot dco_decode_home_snapshot(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Kind dco_decode_kind(dynamic raw);

  @protected
  KindRow dco_decode_kind_row(dynamic raw);

  @protected
  KnowledgeSource dco_decode_knowledge_source(dynamic raw);

  @protected
  LabelRuleRow dco_decode_label_rule_row(dynamic raw);

  @protected
  LanguageRow dco_decode_language_row(dynamic raw);

  @protected
  LayerCount dco_decode_layer_count(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AnswerId> dco_decode_list_answer_id(dynamic raw);

  @protected
  List<EntityRow> dco_decode_list_entity_row(dynamic raw);

  @protected
  List<Finding> dco_decode_list_finding(dynamic raw);

  @protected
  List<KindRow> dco_decode_list_kind_row(dynamic raw);

  @protected
  List<LabelRuleRow> dco_decode_list_label_rule_row(dynamic raw);

  @protected
  List<LanguageRow> dco_decode_list_language_row(dynamic raw);

  @protected
  List<LayerCount> dco_decode_list_layer_count(dynamic raw);

  @protected
  List<Mark> dco_decode_list_mark(dynamic raw);

  @protected
  List<ModelCapability> dco_decode_list_model_capability(dynamic raw);

  @protected
  List<ModelDescriptor> dco_decode_list_model_descriptor(dynamic raw);

  @protected
  List<NameCandidate> dco_decode_list_name_candidate(dynamic raw);

  @protected
  List<PackRow> dco_decode_list_pack_row(dynamic raw);

  @protected
  List<PageEdge> dco_decode_list_page_edge(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProfileRow> dco_decode_list_profile_row(dynamic raw);

  @protected
  List<ProviderFact> dco_decode_list_provider_fact(dynamic raw);

  @protected
  List<ProviderRow> dco_decode_list_provider_row(dynamic raw);

  @protected
  List<RevealedToken> dco_decode_list_revealed_token(dynamic raw);

  @protected
  List<RuleSetRow> dco_decode_list_rule_set_row(dynamic raw);

  @protected
  List<Segment> dco_decode_list_segment(dynamic raw);

  @protected
  List<Span> dco_decode_list_span(dynamic raw);

  @protected
  List<TaughtExceptionRow> dco_decode_list_taught_exception_row(dynamic raw);

  @protected
  List<TaughtNameRow> dco_decode_list_taught_name_row(dynamic raw);

  @protected
  List<TaughtValueRow> dco_decode_list_taught_value_row(dynamic raw);

  @protected
  List<TokenRow> dco_decode_list_token_row(dynamic raw);

  @protected
  List<UserListRow> dco_decode_list_user_list_row(dynamic raw);

  @protected
  List<UserNameRow> dco_decode_list_user_name_row(dynamic raw);

  @protected
  List<ValueRow> dco_decode_list_value_row(dynamic raw);

  @protected
  Mark dco_decode_mark(dynamic raw);

  @protected
  MarkState dco_decode_mark_state(dynamic raw);

  @protected
  ModelAnswer dco_decode_model_answer(dynamic raw);

  @protected
  ModelCapability dco_decode_model_capability(dynamic raw);

  @protected
  ModelDescriptor dco_decode_model_descriptor(dynamic raw);

  @protected
  ModelUsage dco_decode_model_usage(dynamic raw);

  @protected
  NameCandidate dco_decode_name_candidate(dynamic raw);

  @protected
  NameImport dco_decode_name_import(dynamic raw);

  @protected
  NetworkRefusal dco_decode_network_refusal(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AnswerId? dco_decode_opt_box_autoadd_answer_id(dynamic raw);

  @protected
  PayloadHandle? dco_decode_opt_box_autoadd_payload_handle(dynamic raw);

  @protected
  PayloadView? dco_decode_opt_box_autoadd_payload_view(dynamic raw);

  @protected
  Place? dco_decode_opt_box_autoadd_place(dynamic raw);

  @protected
  SessionId? dco_decode_opt_box_autoadd_session_id(dynamic raw);

  @protected
  Source? dco_decode_opt_box_autoadd_source(dynamic raw);

  @protected
  Span? dco_decode_opt_box_autoadd_span(dynamic raw);

  @protected
  TaughtReach? dco_decode_opt_box_autoadd_taught_reach(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PackRow dco_decode_pack_row(dynamic raw);

  @protected
  PageEdge dco_decode_page_edge(dynamic raw);

  @protected
  PayloadHandle dco_decode_payload_handle(dynamic raw);

  @protected
  PayloadView dco_decode_payload_view(dynamic raw);

  @protected
  Place dco_decode_place(dynamic raw);

  @protected
  Policy dco_decode_policy(dynamic raw);

  @protected
  PrivacyRulesSnapshot dco_decode_privacy_rules_snapshot(dynamic raw);

  @protected
  ProfileRow dco_decode_profile_row(dynamic raw);

  @protected
  ProtectOutcome dco_decode_protect_outcome(dynamic raw);

  @protected
  ProviderFact dco_decode_provider_fact(dynamic raw);

  @protected
  ProviderId dco_decode_provider_id(dynamic raw);

  @protected
  ProviderRow dco_decode_provider_row(dynamic raw);

  @protected
  ProviderSnapshot dco_decode_provider_snapshot(dynamic raw);

  @protected
  Refusal dco_decode_refusal(dynamic raw);

  @protected
  ReportSubject dco_decode_report_subject(dynamic raw);

  @protected
  RescanOutcome dco_decode_rescan_outcome(dynamic raw);

  @protected
  RevealState dco_decode_reveal_state(dynamic raw);

  @protected
  RevealedToken dco_decode_revealed_token(dynamic raw);

  @protected
  RevealedValue dco_decode_revealed_value(dynamic raw);

  @protected
  Revision dco_decode_revision(dynamic raw);

  @protected
  RuleSetRow dco_decode_rule_set_row(dynamic raw);

  @protected
  ScanOrigin dco_decode_scan_origin(dynamic raw);

  @protected
  ScanReport dco_decode_scan_report(dynamic raw);

  @protected
  Scope dco_decode_scope(dynamic raw);

  @protected
  Segment dco_decode_segment(dynamic raw);

  @protected
  SelectionView dco_decode_selection_view(dynamic raw);

  @protected
  SessionId dco_decode_session_id(dynamic raw);

  @protected
  Settings dco_decode_settings(dynamic raw);

  @protected
  Source dco_decode_source(dynamic raw);

  @protected
  Span dco_decode_span(dynamic raw);

  @protected
  SwitchOutcome dco_decode_switch_outcome(dynamic raw);

  @protected
  TaughtExceptionRow dco_decode_taught_exception_row(dynamic raw);

  @protected
  TaughtNameRow dco_decode_taught_name_row(dynamic raw);

  @protected
  TaughtReach dco_decode_taught_reach(dynamic raw);

  @protected
  TaughtValueRow dco_decode_taught_value_row(dynamic raw);

  @protected
  TokenRow dco_decode_token_row(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UndoOutcome dco_decode_undo_outcome(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserListRow dco_decode_user_list_row(dynamic raw);

  @protected
  UserNameKind dco_decode_user_name_kind(dynamic raw);

  @protected
  UserNameRow dco_decode_user_name_row(dynamic raw);

  @protected
  ValueRow dco_decode_value_row(dynamic raw);

  @protected
  VaultSnapshot dco_decode_vault_snapshot(dynamic raw);

  @protected
  VaultState dco_decode_vault_state(dynamic raw);

  @protected
  VaultUnlockOutcome dco_decode_vault_unlock_outcome(dynamic raw);

  @protected
  WorkspaceSnapshot dco_decode_workspace_snapshot(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnswerId sse_decode_answer_id(SseDeserializer deserializer);

  @protected
  AnswerSnapshot sse_decode_answer_snapshot(SseDeserializer deserializer);

  @protected
  ApiError sse_decode_api_error(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AnswerId sse_decode_box_autoadd_answer_id(SseDeserializer deserializer);

  @protected
  NetworkRefusal sse_decode_box_autoadd_network_refusal(
    SseDeserializer deserializer,
  );

  @protected
  PayloadHandle sse_decode_box_autoadd_payload_handle(
    SseDeserializer deserializer,
  );

  @protected
  PayloadView sse_decode_box_autoadd_payload_view(SseDeserializer deserializer);

  @protected
  Place sse_decode_box_autoadd_place(SseDeserializer deserializer);

  @protected
  ProviderId sse_decode_box_autoadd_provider_id(SseDeserializer deserializer);

  @protected
  Refusal sse_decode_box_autoadd_refusal(SseDeserializer deserializer);

  @protected
  ReportSubject sse_decode_box_autoadd_report_subject(
    SseDeserializer deserializer,
  );

  @protected
  SessionId sse_decode_box_autoadd_session_id(SseDeserializer deserializer);

  @protected
  Settings sse_decode_box_autoadd_settings(SseDeserializer deserializer);

  @protected
  Source sse_decode_box_autoadd_source(SseDeserializer deserializer);

  @protected
  Span sse_decode_box_autoadd_span(SseDeserializer deserializer);

  @protected
  TaughtReach sse_decode_box_autoadd_taught_reach(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CredentialState sse_decode_credential_state(SseDeserializer deserializer);

  @protected
  DocumentKind sse_decode_document_kind(SseDeserializer deserializer);

  @protected
  DocumentView sse_decode_document_view(SseDeserializer deserializer);

  @protected
  EntityCard sse_decode_entity_card(SseDeserializer deserializer);

  @protected
  EntityKind sse_decode_entity_kind(SseDeserializer deserializer);

  @protected
  EntityRow sse_decode_entity_row(SseDeserializer deserializer);

  @protected
  Explanation sse_decode_explanation(SseDeserializer deserializer);

  @protected
  Finding sse_decode_finding(SseDeserializer deserializer);

  @protected
  FindingAnswer sse_decode_finding_answer(SseDeserializer deserializer);

  @protected
  ForgetPlan sse_decode_forget_plan(SseDeserializer deserializer);

  @protected
  HomeSnapshot sse_decode_home_snapshot(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Kind sse_decode_kind(SseDeserializer deserializer);

  @protected
  KindRow sse_decode_kind_row(SseDeserializer deserializer);

  @protected
  KnowledgeSource sse_decode_knowledge_source(SseDeserializer deserializer);

  @protected
  LabelRuleRow sse_decode_label_rule_row(SseDeserializer deserializer);

  @protected
  LanguageRow sse_decode_language_row(SseDeserializer deserializer);

  @protected
  LayerCount sse_decode_layer_count(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AnswerId> sse_decode_list_answer_id(SseDeserializer deserializer);

  @protected
  List<EntityRow> sse_decode_list_entity_row(SseDeserializer deserializer);

  @protected
  List<Finding> sse_decode_list_finding(SseDeserializer deserializer);

  @protected
  List<KindRow> sse_decode_list_kind_row(SseDeserializer deserializer);

  @protected
  List<LabelRuleRow> sse_decode_list_label_rule_row(
    SseDeserializer deserializer,
  );

  @protected
  List<LanguageRow> sse_decode_list_language_row(SseDeserializer deserializer);

  @protected
  List<LayerCount> sse_decode_list_layer_count(SseDeserializer deserializer);

  @protected
  List<Mark> sse_decode_list_mark(SseDeserializer deserializer);

  @protected
  List<ModelCapability> sse_decode_list_model_capability(
    SseDeserializer deserializer,
  );

  @protected
  List<ModelDescriptor> sse_decode_list_model_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<NameCandidate> sse_decode_list_name_candidate(
    SseDeserializer deserializer,
  );

  @protected
  List<PackRow> sse_decode_list_pack_row(SseDeserializer deserializer);

  @protected
  List<PageEdge> sse_decode_list_page_edge(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProfileRow> sse_decode_list_profile_row(SseDeserializer deserializer);

  @protected
  List<ProviderFact> sse_decode_list_provider_fact(
    SseDeserializer deserializer,
  );

  @protected
  List<ProviderRow> sse_decode_list_provider_row(SseDeserializer deserializer);

  @protected
  List<RevealedToken> sse_decode_list_revealed_token(
    SseDeserializer deserializer,
  );

  @protected
  List<RuleSetRow> sse_decode_list_rule_set_row(SseDeserializer deserializer);

  @protected
  List<Segment> sse_decode_list_segment(SseDeserializer deserializer);

  @protected
  List<Span> sse_decode_list_span(SseDeserializer deserializer);

  @protected
  List<TaughtExceptionRow> sse_decode_list_taught_exception_row(
    SseDeserializer deserializer,
  );

  @protected
  List<TaughtNameRow> sse_decode_list_taught_name_row(
    SseDeserializer deserializer,
  );

  @protected
  List<TaughtValueRow> sse_decode_list_taught_value_row(
    SseDeserializer deserializer,
  );

  @protected
  List<TokenRow> sse_decode_list_token_row(SseDeserializer deserializer);

  @protected
  List<UserListRow> sse_decode_list_user_list_row(SseDeserializer deserializer);

  @protected
  List<UserNameRow> sse_decode_list_user_name_row(SseDeserializer deserializer);

  @protected
  List<ValueRow> sse_decode_list_value_row(SseDeserializer deserializer);

  @protected
  Mark sse_decode_mark(SseDeserializer deserializer);

  @protected
  MarkState sse_decode_mark_state(SseDeserializer deserializer);

  @protected
  ModelAnswer sse_decode_model_answer(SseDeserializer deserializer);

  @protected
  ModelCapability sse_decode_model_capability(SseDeserializer deserializer);

  @protected
  ModelDescriptor sse_decode_model_descriptor(SseDeserializer deserializer);

  @protected
  ModelUsage sse_decode_model_usage(SseDeserializer deserializer);

  @protected
  NameCandidate sse_decode_name_candidate(SseDeserializer deserializer);

  @protected
  NameImport sse_decode_name_import(SseDeserializer deserializer);

  @protected
  NetworkRefusal sse_decode_network_refusal(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AnswerId? sse_decode_opt_box_autoadd_answer_id(SseDeserializer deserializer);

  @protected
  PayloadHandle? sse_decode_opt_box_autoadd_payload_handle(
    SseDeserializer deserializer,
  );

  @protected
  PayloadView? sse_decode_opt_box_autoadd_payload_view(
    SseDeserializer deserializer,
  );

  @protected
  Place? sse_decode_opt_box_autoadd_place(SseDeserializer deserializer);

  @protected
  SessionId? sse_decode_opt_box_autoadd_session_id(
    SseDeserializer deserializer,
  );

  @protected
  Source? sse_decode_opt_box_autoadd_source(SseDeserializer deserializer);

  @protected
  Span? sse_decode_opt_box_autoadd_span(SseDeserializer deserializer);

  @protected
  TaughtReach? sse_decode_opt_box_autoadd_taught_reach(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PackRow sse_decode_pack_row(SseDeserializer deserializer);

  @protected
  PageEdge sse_decode_page_edge(SseDeserializer deserializer);

  @protected
  PayloadHandle sse_decode_payload_handle(SseDeserializer deserializer);

  @protected
  PayloadView sse_decode_payload_view(SseDeserializer deserializer);

  @protected
  Place sse_decode_place(SseDeserializer deserializer);

  @protected
  Policy sse_decode_policy(SseDeserializer deserializer);

  @protected
  PrivacyRulesSnapshot sse_decode_privacy_rules_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  ProfileRow sse_decode_profile_row(SseDeserializer deserializer);

  @protected
  ProtectOutcome sse_decode_protect_outcome(SseDeserializer deserializer);

  @protected
  ProviderFact sse_decode_provider_fact(SseDeserializer deserializer);

  @protected
  ProviderId sse_decode_provider_id(SseDeserializer deserializer);

  @protected
  ProviderRow sse_decode_provider_row(SseDeserializer deserializer);

  @protected
  ProviderSnapshot sse_decode_provider_snapshot(SseDeserializer deserializer);

  @protected
  Refusal sse_decode_refusal(SseDeserializer deserializer);

  @protected
  ReportSubject sse_decode_report_subject(SseDeserializer deserializer);

  @protected
  RescanOutcome sse_decode_rescan_outcome(SseDeserializer deserializer);

  @protected
  RevealState sse_decode_reveal_state(SseDeserializer deserializer);

  @protected
  RevealedToken sse_decode_revealed_token(SseDeserializer deserializer);

  @protected
  RevealedValue sse_decode_revealed_value(SseDeserializer deserializer);

  @protected
  Revision sse_decode_revision(SseDeserializer deserializer);

  @protected
  RuleSetRow sse_decode_rule_set_row(SseDeserializer deserializer);

  @protected
  ScanOrigin sse_decode_scan_origin(SseDeserializer deserializer);

  @protected
  ScanReport sse_decode_scan_report(SseDeserializer deserializer);

  @protected
  Scope sse_decode_scope(SseDeserializer deserializer);

  @protected
  Segment sse_decode_segment(SseDeserializer deserializer);

  @protected
  SelectionView sse_decode_selection_view(SseDeserializer deserializer);

  @protected
  SessionId sse_decode_session_id(SseDeserializer deserializer);

  @protected
  Settings sse_decode_settings(SseDeserializer deserializer);

  @protected
  Source sse_decode_source(SseDeserializer deserializer);

  @protected
  Span sse_decode_span(SseDeserializer deserializer);

  @protected
  SwitchOutcome sse_decode_switch_outcome(SseDeserializer deserializer);

  @protected
  TaughtExceptionRow sse_decode_taught_exception_row(
    SseDeserializer deserializer,
  );

  @protected
  TaughtNameRow sse_decode_taught_name_row(SseDeserializer deserializer);

  @protected
  TaughtReach sse_decode_taught_reach(SseDeserializer deserializer);

  @protected
  TaughtValueRow sse_decode_taught_value_row(SseDeserializer deserializer);

  @protected
  TokenRow sse_decode_token_row(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UndoOutcome sse_decode_undo_outcome(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserListRow sse_decode_user_list_row(SseDeserializer deserializer);

  @protected
  UserNameKind sse_decode_user_name_kind(SseDeserializer deserializer);

  @protected
  UserNameRow sse_decode_user_name_row(SseDeserializer deserializer);

  @protected
  ValueRow sse_decode_value_row(SseDeserializer deserializer);

  @protected
  VaultSnapshot sse_decode_vault_snapshot(SseDeserializer deserializer);

  @protected
  VaultState sse_decode_vault_state(SseDeserializer deserializer);

  @protected
  VaultUnlockOutcome sse_decode_vault_unlock_outcome(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceSnapshot sse_decode_workspace_snapshot(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_answer_id(AnswerId self, SseSerializer serializer);

  @protected
  void sse_encode_answer_snapshot(
    AnswerSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_error(ApiError self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_answer_id(
    AnswerId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_network_refusal(
    NetworkRefusal self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_payload_handle(
    PayloadHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_payload_view(
    PayloadView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_place(Place self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_provider_id(
    ProviderId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_refusal(Refusal self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_report_subject(
    ReportSubject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_id(
    SessionId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings(Settings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_source(Source self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_span(Span self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_taught_reach(
    TaughtReach self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_credential_state(
    CredentialState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_document_kind(DocumentKind self, SseSerializer serializer);

  @protected
  void sse_encode_document_view(DocumentView self, SseSerializer serializer);

  @protected
  void sse_encode_entity_card(EntityCard self, SseSerializer serializer);

  @protected
  void sse_encode_entity_kind(EntityKind self, SseSerializer serializer);

  @protected
  void sse_encode_entity_row(EntityRow self, SseSerializer serializer);

  @protected
  void sse_encode_explanation(Explanation self, SseSerializer serializer);

  @protected
  void sse_encode_finding(Finding self, SseSerializer serializer);

  @protected
  void sse_encode_finding_answer(FindingAnswer self, SseSerializer serializer);

  @protected
  void sse_encode_forget_plan(ForgetPlan self, SseSerializer serializer);

  @protected
  void sse_encode_home_snapshot(HomeSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_kind(Kind self, SseSerializer serializer);

  @protected
  void sse_encode_kind_row(KindRow self, SseSerializer serializer);

  @protected
  void sse_encode_knowledge_source(
    KnowledgeSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_label_rule_row(LabelRuleRow self, SseSerializer serializer);

  @protected
  void sse_encode_language_row(LanguageRow self, SseSerializer serializer);

  @protected
  void sse_encode_layer_count(LayerCount self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_answer_id(List<AnswerId> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entity_row(
    List<EntityRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_finding(List<Finding> self, SseSerializer serializer);

  @protected
  void sse_encode_list_kind_row(List<KindRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_label_rule_row(
    List<LabelRuleRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_language_row(
    List<LanguageRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_layer_count(
    List<LayerCount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mark(List<Mark> self, SseSerializer serializer);

  @protected
  void sse_encode_list_model_capability(
    List<ModelCapability> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_model_descriptor(
    List<ModelDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_name_candidate(
    List<NameCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pack_row(List<PackRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_page_edge(List<PageEdge> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_profile_row(
    List<ProfileRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_fact(
    List<ProviderFact> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_row(
    List<ProviderRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_revealed_token(
    List<RevealedToken> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rule_set_row(
    List<RuleSetRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_segment(List<Segment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_span(List<Span> self, SseSerializer serializer);

  @protected
  void sse_encode_list_taught_exception_row(
    List<TaughtExceptionRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_taught_name_row(
    List<TaughtNameRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_taught_value_row(
    List<TaughtValueRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_token_row(List<TokenRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_user_list_row(
    List<UserListRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_name_row(
    List<UserNameRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_value_row(List<ValueRow> self, SseSerializer serializer);

  @protected
  void sse_encode_mark(Mark self, SseSerializer serializer);

  @protected
  void sse_encode_mark_state(MarkState self, SseSerializer serializer);

  @protected
  void sse_encode_model_answer(ModelAnswer self, SseSerializer serializer);

  @protected
  void sse_encode_model_capability(
    ModelCapability self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_descriptor(
    ModelDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_usage(ModelUsage self, SseSerializer serializer);

  @protected
  void sse_encode_name_candidate(NameCandidate self, SseSerializer serializer);

  @protected
  void sse_encode_name_import(NameImport self, SseSerializer serializer);

  @protected
  void sse_encode_network_refusal(
    NetworkRefusal self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_answer_id(
    AnswerId? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_payload_handle(
    PayloadHandle? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_payload_view(
    PayloadView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_place(Place? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_session_id(
    SessionId? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_source(
    Source? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_span(Span? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_taught_reach(
    TaughtReach? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_pack_row(PackRow self, SseSerializer serializer);

  @protected
  void sse_encode_page_edge(PageEdge self, SseSerializer serializer);

  @protected
  void sse_encode_payload_handle(PayloadHandle self, SseSerializer serializer);

  @protected
  void sse_encode_payload_view(PayloadView self, SseSerializer serializer);

  @protected
  void sse_encode_place(Place self, SseSerializer serializer);

  @protected
  void sse_encode_policy(Policy self, SseSerializer serializer);

  @protected
  void sse_encode_privacy_rules_snapshot(
    PrivacyRulesSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_profile_row(ProfileRow self, SseSerializer serializer);

  @protected
  void sse_encode_protect_outcome(
    ProtectOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_fact(ProviderFact self, SseSerializer serializer);

  @protected
  void sse_encode_provider_id(ProviderId self, SseSerializer serializer);

  @protected
  void sse_encode_provider_row(ProviderRow self, SseSerializer serializer);

  @protected
  void sse_encode_provider_snapshot(
    ProviderSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_refusal(Refusal self, SseSerializer serializer);

  @protected
  void sse_encode_report_subject(ReportSubject self, SseSerializer serializer);

  @protected
  void sse_encode_rescan_outcome(RescanOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_reveal_state(RevealState self, SseSerializer serializer);

  @protected
  void sse_encode_revealed_token(RevealedToken self, SseSerializer serializer);

  @protected
  void sse_encode_revealed_value(RevealedValue self, SseSerializer serializer);

  @protected
  void sse_encode_revision(Revision self, SseSerializer serializer);

  @protected
  void sse_encode_rule_set_row(RuleSetRow self, SseSerializer serializer);

  @protected
  void sse_encode_scan_origin(ScanOrigin self, SseSerializer serializer);

  @protected
  void sse_encode_scan_report(ScanReport self, SseSerializer serializer);

  @protected
  void sse_encode_scope(Scope self, SseSerializer serializer);

  @protected
  void sse_encode_segment(Segment self, SseSerializer serializer);

  @protected
  void sse_encode_selection_view(SelectionView self, SseSerializer serializer);

  @protected
  void sse_encode_session_id(SessionId self, SseSerializer serializer);

  @protected
  void sse_encode_settings(Settings self, SseSerializer serializer);

  @protected
  void sse_encode_source(Source self, SseSerializer serializer);

  @protected
  void sse_encode_span(Span self, SseSerializer serializer);

  @protected
  void sse_encode_switch_outcome(SwitchOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_taught_exception_row(
    TaughtExceptionRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_taught_name_row(TaughtNameRow self, SseSerializer serializer);

  @protected
  void sse_encode_taught_reach(TaughtReach self, SseSerializer serializer);

  @protected
  void sse_encode_taught_value_row(
    TaughtValueRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_token_row(TokenRow self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_undo_outcome(UndoOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_list_row(UserListRow self, SseSerializer serializer);

  @protected
  void sse_encode_user_name_kind(UserNameKind self, SseSerializer serializer);

  @protected
  void sse_encode_user_name_row(UserNameRow self, SseSerializer serializer);

  @protected
  void sse_encode_value_row(ValueRow self, SseSerializer serializer);

  @protected
  void sse_encode_vault_snapshot(VaultSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_vault_state(VaultState self, SseSerializer serializer);

  @protected
  void sse_encode_vault_unlock_outcome(
    VaultUnlockOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_snapshot(
    WorkspaceSnapshot self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
