// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Shown by the UI so a build can be identified on sight. Proof that the
/// Flutter window is reading from Rust and not from a Dart constant.
String coreVersion() => RustLib.instance.api.crateApiCoreCoreVersion();
