// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mirrors.freezed.dart';

class AnswerId {
  final int id;

  const AnswerId({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnswerId && runtimeType == other.runtimeType && id == other.id;
}

class AnswerSnapshot {
  final int stateRevision;
  final AnswerId answer;
  final int index;
  final int total;

  /// The answer before this one, or `None` at the first.
  ///
  /// Carried here rather than worked out by a screen, for the reason the
  /// whole snapshot exists: `index`/`total` and «which answer do I move to»
  /// must be **one** fact. A list held in Dart alongside a count from Rust
  /// is two sources that will disagree, and «Answer 2 of 2» with a stale
  /// neighbour is the same family as every lie this project has hunted.
  final AnswerId? previous;

  /// The answer after this one, or `None` at the last.
  final AnswerId? next;
  final List<Segment> restored;
  final String asWritten;

  /// **Every token in this answer that this conversation could not resolve**
  /// — 046/U, by name and in the order they appear.
  ///
  /// Empty is the ordinary case and the only one a person need not be told
  /// about. Non-empty means the answer was built somewhere else: a screen
  /// that drew these as the model's own words would be telling a person that
  /// `__Z_5CDD_IBAN_5B32__` is what the model said about their account.
  ///
  /// Named here as well as marked in the pieces so that the count in the
  /// sentence and the marks in the text are **one** fact.
  final List<String> unknownTokens;

  const AnswerSnapshot({
    required this.stateRevision,
    required this.answer,
    required this.index,
    required this.total,
    this.previous,
    this.next,
    required this.restored,
    required this.asWritten,
    required this.unknownTokens,
  });

  @override
  int get hashCode =>
      stateRevision.hashCode ^
      answer.hashCode ^
      index.hashCode ^
      total.hashCode ^
      previous.hashCode ^
      next.hashCode ^
      restored.hashCode ^
      asWritten.hashCode ^
      unknownTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnswerSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          answer == other.answer &&
          index == other.index &&
          total == other.total &&
          previous == other.previous &&
          next == other.next &&
          restored == other.restored &&
          asWritten == other.asWritten &&
          unknownTokens == other.unknownTokens;
}

@freezed
sealed class ApiError with _$ApiError implements FrbException {
  const ApiError._();

  /// The function exists in the contract but its stage has not been built yet.
  const factory ApiError.notImplemented() = ApiError_NotImplemented;

  /// No such session, or it was closed.
  const factory ApiError.invalidSession() = ApiError_InvalidSession;

  /// No such payload.
  const factory ApiError.invalidHandle() = ApiError_InvalidHandle;

  /// The document changed after this payload was built. Build a new one.
  const factory ApiError.stalePayload({
    required int expected,
    required int got,
  }) = ApiError_StalePayload;

  /// The vault must be opened before this can be answered.
  const factory ApiError.vaultLocked() = ApiError_VaultLocked;

  /// The chosen provider has no key, or is not reachable.
  const factory ApiError.providerUnavailable({required String provider}) =
      ApiError_ProviderUnavailable;

  /// Suggestions are still unanswered; there is no way past them.
  const factory ApiError.openSuggestions({required int count}) =
      ApiError_OpenSuggestions;

  /// What was given cannot be used, and why: an empty value, a name left
  /// blank, a passphrase too short, a credential missing where one is
  /// needed, a scope that does not apply in this conversation.
  ///
  /// The person's next move is to change what they entered.
  const factory ApiError.inputRefused({required String reason}) =
      ApiError_InputRefused;

  /// Something was named that is not here — a profile, a rule set, a pack, a
  /// taught rule. `UnknownToken` is this same shape for a token in a session.
  ///
  /// The person's next move is to name something else.
  const factory ApiError.notFound({required String reason}) = ApiError_NotFound;

  /// There is no vault on this device yet, so there is nothing to open, to
  /// change, or to keep anything in.
  ///
  /// Three neighbours, deliberately apart: this one means **there is none**,
  /// `VaultLocked` means there is one and it is shut, and `VaultRequired`
  /// means an act needs one open and none is.
  const factory ApiError.vaultAbsent() = ApiError_VaultAbsent;

  /// A vault is already on this device, and making another would write over
  /// it. Refused rather than merged: there is no way back from that.
  const factory ApiError.vaultAlreadyExists() = ApiError_VaultAlreadyExists;

  /// A place Z Privacy keeps its **own** files cannot be used safely — a
  /// symlink where a directory belongs, permissions that let someone else
  /// read it, a temporary file left by another program.
  ///
  /// Nothing the person typed is wrong here, so it is not `InputRefused`.
  const factory ApiError.storageRefused({required String reason}) =
      ApiError_StorageRefused;

  /// A document was not imported, with the named reason and a detail for the
  /// user («page 3 of 20 has no text layer»).
  const factory ApiError.documentRefused({
    required Refusal reason,
    required String detail,
  }) = ApiError_DocumentRefused;

  /// A span outside the text, reversed, or inside a character.
  const factory ApiError.badSpan({required String reason}) = ApiError_BadSpan;

  /// No such token in this session.
  const factory ApiError.unknownToken() = ApiError_UnknownToken;

  /// Nothing is protected and nothing is written; there is nothing to build.
  const factory ApiError.nothingToSend() = ApiError_NothingToSend;

  /// The built payload failed the core's own leak audit and was thrown away.
  /// This should never reach a user; if it does, the bug stayed inside.
  const factory ApiError.payloadRefused({required String reason}) =
      ApiError_PayloadRefused;

  /// The network did not carry the question, and why. Never a response body:
  /// a provider's error page can quote the request back, so nothing that comes
  /// off the wire is allowed into this message.
  const factory ApiError.networkRefused({
    required NetworkRefusal reason,
    required String detail,
  }) = ApiError_NetworkRefused;

  /// A vault file asked for KDF costs this build does not support.
  const factory ApiError.unsupportedKdfParameters({required String reason}) =
      ApiError_UnsupportedKdfParameters;

  /// A vault file had bytes after the end of the versioned ZVLT structure.
  const factory ApiError.trailingVaultData() = ApiError_TrailingVaultData;

  /// The vault could not be authenticated after key derivation.
  ///
  /// This does not distinguish a wrong passphrase from a modified vault: the
  /// AEAD tag proves only that opening failed, not which human story caused it.
  const factory ApiError.vaultAuthenticationFailed() =
      ApiError_VaultAuthenticationFailed;

  /// This payload handle already drove a send, or is driving one now.
  const factory ApiError.payloadAlreadySent() = ApiError_PayloadAlreadySent;

  /// The act needs an open vault — Always, Profile, or anything kept for tomorrow —
  /// and there is not one. Named so a press that cannot keep its promise cannot
  /// look like success.
  const factory ApiError.vaultRequired() = ApiError_VaultRequired;

  /// **A press in the whitespace between two columns** (046/Q). The span was
  /// read without trouble; there is simply no value where it points, and
  /// resolving it to the nearest cell would be the app choosing a column for
  /// the person.
  ///
  /// Not `BadSpan`: that one means a selection this crate could not read — out
  /// of range, reversed, or cut through a character — and its sentence tells
  /// the person to select again, which is wrong advice here. The same
  /// reasoning that split `ImportRefused` on 30 September: a different story
  /// needs a different type, because the screen can only say why if the type
  /// says why.
  const factory ApiError.betweenColumns() = ApiError_BetweenColumns;
}

enum CredentialState {
  /// No credential is stored for this provider, in the vault or in memory.
  missing,

  /// Kept in process memory for this run only.
  sessionOnly,

  /// Sealed inside the vault.
  encryptedInVault,
}

enum DocumentKind { txt, docx, pdf }

class DocumentView {
  final String text;
  final List<Mark> marks;

  /// What the user called it: a file name, or empty for text typed in.
  final String name;
  final DocumentKind kind;
  final int pages;

  const DocumentView({
    required this.text,
    required this.marks,
    required this.name,
    required this.kind,
    required this.pages,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      marks.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentView &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          marks == other.marks &&
          name == other.name &&
          kind == other.kind &&
          pages == other.pages;
}

class EntityCard {
  final int id;
  final EntityKind kind;
  final String label;
  final String? profileId;
  final List<ValueRow> values;

  const EntityCard({
    required this.id,
    required this.kind,
    required this.label,
    this.profileId,
    required this.values,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      label.hashCode ^
      profileId.hashCode ^
      values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityCard &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          label == other.label &&
          profileId == other.profileId &&
          values == other.values;
}

enum EntityKind { client, person, company, project, custom }

class EntityRow {
  final int id;
  final EntityKind kind;
  final String label;
  final String? profileId;
  final int values;

  /// «4 always · 1 suggest», as the vault list shows it.
  final String policySummary;

  const EntityRow({
    required this.id,
    required this.kind,
    required this.label,
    this.profileId,
    required this.values,
    required this.policySummary,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      label.hashCode ^
      profileId.hashCode ^
      values.hashCode ^
      policySummary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          label == other.label &&
          profileId == other.profileId &&
          values == other.values &&
          policySummary == other.policySummary;
}

class Explanation {
  /// «You taught this value» · «German privacy rule» · «You protected this
  /// by hand» · «A shape that needs no language».
  final String headline;

  /// The particulars, one per line: «Valid IBAN checksum», «German label:
  /// Mobil», «Two rules agree». Empty is not allowed to happen — a protection
  /// with nothing to say about itself is the black box arriving.
  final List<String> because;
  final Kind kind;
  final Scope scope;

  /// Where it applies: «This document only» · «Client Nordstern» · «Everywhere».
  final String applies;

  /// Whether a person decided this, or a layer did.
  final bool decided;
  final String token;

  /// When it was taught, in seconds since 1970. 0 when it was not taught at
  /// all (a rule found it) or when the vault predates the date being kept.
  final BigInt learnedAt;

  /// The identity and value it came from, when the vault taught it. This is
  /// what «Edit» and «Forget» act on.
  final int? entity;
  final int? valueId;

  /// Other spellings of the same value. Shown behind one tap, like every
  /// other value in this app.
  final List<String> aliases;

  /// The reach of the taught value, when one was taught — so the «Forget»
  /// button can carry its own scope in its name instead of leaving a person
  /// to assemble the meaning from a line of small print. `None` when nothing
  /// was taught, which is the same case as `entity`/`value_id` being `None`.
  final TaughtReach? taughtReach;

  const Explanation({
    required this.headline,
    required this.because,
    required this.kind,
    required this.scope,
    required this.applies,
    required this.decided,
    required this.token,
    required this.learnedAt,
    this.entity,
    this.valueId,
    required this.aliases,
    this.taughtReach,
  });

  @override
  int get hashCode =>
      headline.hashCode ^
      because.hashCode ^
      kind.hashCode ^
      scope.hashCode ^
      applies.hashCode ^
      decided.hashCode ^
      token.hashCode ^
      learnedAt.hashCode ^
      entity.hashCode ^
      valueId.hashCode ^
      aliases.hashCode ^
      taughtReach.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Explanation &&
          runtimeType == other.runtimeType &&
          headline == other.headline &&
          because == other.because &&
          kind == other.kind &&
          scope == other.scope &&
          applies == other.applies &&
          decided == other.decided &&
          token == other.token &&
          learnedAt == other.learnedAt &&
          entity == other.entity &&
          valueId == other.valueId &&
          aliases == other.aliases &&
          taughtReach == other.taughtReach;
}

class Finding {
  final int id;
  final Span span;
  final Kind kind;

  /// Who found it.
  final Source source;

  /// Whether a person decided it. The review list groups by this, not by
  /// `source`: confirming the pack's suggestion is **your** decision.
  final bool decided;
  final String reason;
  final MarkState state;

  /// The vault identities that claim this text.
  ///
  /// Empty when no identity is involved; one when the vault knows it; **more
  /// than one is a conflict** — two identities claim the same spelling, and the
  /// scanner refuses to choose silently. The app must ask.
  final List<String> entities;

  /// Where it sits: page and paragraph. Kept through protection, so a review
  /// list can still jump to page 17 after everything is replaced.
  final Place? place;

  /// How many places in this document hold this same value, in this same
  /// state — this one included, so it is never 0.
  ///
  /// For a suggestion it is the size of the decision: one answer settles all
  /// of them, because a person deciding about «Lindenstraße 8» has decided
  /// about «Lindenstraße 8», not about a byte range. The card says «in N
  /// places» from this number, and Dart counts nothing itself.
  final int occurrences;

  const Finding({
    required this.id,
    required this.span,
    required this.kind,
    required this.source,
    required this.decided,
    required this.reason,
    required this.state,
    required this.entities,
    this.place,
    required this.occurrences,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      span.hashCode ^
      kind.hashCode ^
      source.hashCode ^
      decided.hashCode ^
      reason.hashCode ^
      state.hashCode ^
      entities.hashCode ^
      place.hashCode ^
      occurrences.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Finding &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          span == other.span &&
          kind == other.kind &&
          source == other.source &&
          decided == other.decided &&
          reason == other.reason &&
          state == other.state &&
          entities == other.entities &&
          place == other.place &&
          occurrences == other.occurrences;
}

enum FindingAnswer { protect, always, notSensitive, skip }

class ForgetPlan {
  /// What it is, so the sheet can name it back to the user.
  final String what;
  final int values;
  final int aliases;

  /// Identities that would be left holding nothing, and so go too.
  final int identities;

  /// The profiles it is associated with, by name.
  final List<String> profiles;

  /// What is **not** touched, said out loud because the user is about to
  /// press a button that says «forget».
  final List<String> keeps;

  /// Permanent knowledge that could recognise this value **in future**.
  ///
  /// The definition is strict on purpose (the owner, 28 Sep). Empty means:
  /// *no permanent knowledge **in the current vault** will recognise this
  /// value again.* It is not a claim about every copy of the vault that has
  /// ever existed: an older valid one may be restored and bring the value
  /// back, which is F-02 and is stated as an accepted limitation rather than
  /// quietly contradicted here. It does
  /// **not** mean the value is nowhere in the program — the open
  /// conversation's token store still holds it, and an answer already
  /// received still reads as it did. Those are not knowledge for tomorrow;
  /// they are today's work, and `keeps` says so in words.
  ///
  /// Must be empty after forgetting. Reported rather than assumed, and both a
  /// test and the screen check it.
  final List<String> stillKnownBy;

  const ForgetPlan({
    required this.what,
    required this.values,
    required this.aliases,
    required this.identities,
    required this.profiles,
    required this.keeps,
    required this.stillKnownBy,
  });

  @override
  int get hashCode =>
      what.hashCode ^
      values.hashCode ^
      aliases.hashCode ^
      identities.hashCode ^
      profiles.hashCode ^
      keeps.hashCode ^
      stillKnownBy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForgetPlan &&
          runtimeType == other.runtimeType &&
          what == other.what &&
          values == other.values &&
          aliases == other.aliases &&
          identities == other.identities &&
          profiles == other.profiles &&
          keeps == other.keeps &&
          stillKnownBy == other.stillKnownBy;
}

class HomeSnapshot {
  final int stateRevision;
  final VaultState vault;
  final int identityCount;
  final int valueCount;
  final List<ProfileRow> profiles;
  final List<PackRow> packs;
  final List<ProviderFact> providers;
  final Settings settings;
  final List<KindRow> kinds;

  const HomeSnapshot({
    required this.stateRevision,
    required this.vault,
    required this.identityCount,
    required this.valueCount,
    required this.profiles,
    required this.packs,
    required this.providers,
    required this.settings,
    required this.kinds,
  });

  @override
  int get hashCode =>
      stateRevision.hashCode ^
      vault.hashCode ^
      identityCount.hashCode ^
      valueCount.hashCode ^
      profiles.hashCode ^
      packs.hashCode ^
      providers.hashCode ^
      settings.hashCode ^
      kinds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          vault == other.vault &&
          identityCount == other.identityCount &&
          valueCount == other.valueCount &&
          profiles == other.profiles &&
          packs == other.packs &&
          providers == other.providers &&
          settings == other.settings &&
          kinds == other.kinds;
}

enum Kind {
  person,
  company,
  email,
  phone,

  /// An IBAN — an account, internationally addressed.
  iban,

  /// A bank's own identifier (SWIFT/BIC). Not an IBAN, and not the same secret.
  bic,

  /// A plain account number, as a German letter writes it after «Kontonummer:».
  account,
  taxId,
  customerNo,
  address,
  contract,
  project,
  client,

  /// A national identity card number — `Personalausweisnummer L01X00T47`.
  idCard,

  /// A date of birth. The date alone: «geboren am» stays in the clear, as a
  /// salutation does, so the sentence still reads.
  birthdate,

  /// A vehicle's registration plate.
  vehicle,

  /// A German social-insurance number — *Sozialversicherungsnummer*, the one
  /// a payslip carries: an area number, the bearer's birth date, the first
  /// letter of their birth name, a serial and a check digit over all of it.
  ///
  /// It carries a birth date inside it, so it is not only an identifier: a
  /// person whose number is read has had their date of birth read with it.
  socialInsuranceNo,

  /// A personnel number — *Personalnummer*, what a payroll ledger calls an
  /// employee. Not a customer number: the word is read twice, once in the
  /// explain card and once in the token the model is asked about, and
  /// «customer» is wrong in both on a payslip.
  employeeNo,
  custom,
}

class KindRow {
  final Kind kind;

  /// What to call it. The core's word, not the screen's.
  final String label;

  /// True for a kind the user made. Always false today; the field exists so
  /// that the day it is true, nothing above it needs rewriting.
  final bool custom;

  const KindRow({
    required this.kind,
    required this.label,
    required this.custom,
  });

  @override
  int get hashCode => kind.hashCode ^ label.hashCode ^ custom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KindRow &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          label == other.label &&
          custom == other.custom;
}

enum KnowledgeSource { builtIn, userTaughtValue, userException }

class LabelRuleRow {
  final int id;

  /// The word as they typed it.
  final String label;
  final Kind kind;

  /// `None` is everywhere; `Some` names the profile it belongs to.
  final String? profileId;
  final String? profileName;

  /// Days since the epoch, 0 when unknown — never today's date guessed in.
  final BigInt learnedAt;

  const LabelRuleRow({
    required this.id,
    required this.label,
    required this.kind,
    this.profileId,
    this.profileName,
    required this.learnedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      kind.hashCode ^
      profileId.hashCode ^
      profileName.hashCode ^
      learnedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LabelRuleRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          kind == other.kind &&
          profileId == other.profileId &&
          profileName == other.profileName &&
          learnedAt == other.learnedAt;
}

class LanguageRow {
  /// ISO 639-1.
  final String id;

  /// The language's own name for itself — what a person looks for.
  final String label;

  /// Does this build carry rules of its own for it? False means the general
  /// rules, the vault and the person's own list, and no dictionary.
  final bool hasRules;

  const LanguageRow({
    required this.id,
    required this.label,
    required this.hasRules,
  });

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ hasRules.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LanguageRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          hasRules == other.hasRules;
}

class LayerCount {
  final Source source;
  final String detail;
  final int count;

  const LayerCount({
    required this.source,
    required this.detail,
    required this.count,
  });

  @override
  int get hashCode => source.hashCode ^ detail.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayerCount &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          detail == other.detail &&
          count == other.count;
}

class LineSelection {
  /// How many lines are selected. «All» is simply every line.
  final int lines;

  /// Values already protected inside them.
  final int protected;

  /// Values inside them still waiting for an answer.
  final int open;

  const LineSelection({
    required this.lines,
    required this.protected,
    required this.open,
  });

  @override
  int get hashCode => lines.hashCode ^ protected.hashCode ^ open.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineSelection &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          protected == other.protected &&
          open == other.open;
}

class Mark {
  final Span span;
  final MarkState state;
  final String? token;
  final Kind kind;

  /// Who **found** it.
  final Source source;

  /// Whether a person **decided** it, as against a layer deciding on its own.
  ///
  /// Two different questions, and mixing them wrote a false history: the pack
  /// may have found a name while you chose to protect it, and a list that
  /// said «you found this» would be wrong. It is also a rule and not only a
  /// label — see [`Scope`] and the rescan behaviour. (Task 033/034.)
  final bool decided;

  /// Pack id, entity id, or the rule's name — the "why" behind the mark.
  final String sourceDetail;

  /// The page and paragraph it sits on, when the text came from a document.
  final Place? place;

  const Mark({
    required this.span,
    required this.state,
    this.token,
    required this.kind,
    required this.source,
    required this.decided,
    required this.sourceDetail,
    this.place,
  });

  @override
  int get hashCode =>
      span.hashCode ^
      state.hashCode ^
      token.hashCode ^
      kind.hashCode ^
      source.hashCode ^
      decided.hashCode ^
      sourceDetail.hashCode ^
      place.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Mark &&
          runtimeType == other.runtimeType &&
          span == other.span &&
          state == other.state &&
          token == other.token &&
          kind == other.kind &&
          source == other.source &&
          decided == other.decided &&
          sourceDetail == other.sourceDetail &&
          place == other.place;
}

enum MarkState { protected, suggested }

class ModelAnswer {
  final AnswerId? answer;

  /// The model's words as they arrived. For a protected request this is the
  /// text with tokens still in it — the restored view is a different call,
  /// and this one is what the model actually wrote.
  final String text;
  final ModelUsage usage;

  const ModelAnswer({this.answer, required this.text, required this.usage});

  @override
  int get hashCode => answer.hashCode ^ text.hashCode ^ usage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelAnswer &&
          runtimeType == other.runtimeType &&
          answer == other.answer &&
          text == other.text &&
          usage == other.usage;
}

enum ModelCapability {
  /// Text in, text out. Every model in V1 has this and only this is used.
  text,

  /// Accepts images as well as text.
  vision,

  /// Can be given tools to call.
  tools,

  /// Asked to reason at length before answering.
  reasoning,
}

class ModelDescriptor {
  final String providerId;
  final String modelId;

  /// What a person reads in a list.
  final String displayName;
  final List<ModelCapability> capabilities;

  /// The context window the provider states, in thousands of tokens. 0 where
  /// the provider does not say — a number we do not have is not a number we
  /// invent.
  final int contextK;

  /// Whether this model, at this provider's address, needs a credential.
  final bool credentialRequired;

  /// Usable in this run: the provider is connected, or needs no credential.
  final bool available;

  const ModelDescriptor({
    required this.providerId,
    required this.modelId,
    required this.displayName,
    required this.capabilities,
    required this.contextK,
    required this.credentialRequired,
    required this.available,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      modelId.hashCode ^
      displayName.hashCode ^
      capabilities.hashCode ^
      contextK.hashCode ^
      credentialRequired.hashCode ^
      available.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelDescriptor &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          modelId == other.modelId &&
          displayName == other.displayName &&
          capabilities == other.capabilities &&
          contextK == other.contextK &&
          credentialRequired == other.credentialRequired &&
          available == other.available;
}

class ModelUsage {
  final String providerId;
  final String modelId;
  final int inputUnits;
  final int outputUnits;

  /// How long the request took, end to end, in milliseconds.
  final int millis;
  final bool ok;

  const ModelUsage({
    required this.providerId,
    required this.modelId,
    required this.inputUnits,
    required this.outputUnits,
    required this.millis,
    required this.ok,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      modelId.hashCode ^
      inputUnits.hashCode ^
      outputUnits.hashCode ^
      millis.hashCode ^
      ok.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelUsage &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          modelId == other.modelId &&
          inputUnits == other.inputUnits &&
          outputUnits == other.outputUnits &&
          millis == other.millis &&
          ok == other.ok;
}

class NameCandidate {
  /// The word, as the document writes it.
  final String text;

  /// What the document is using it as. A surname, so far: the two rules that
  /// find candidates both read the position of a known given name.
  final bool family;

  /// How many times the word stands in this document.
  final int occurrences;

  /// How many pages it stands on, which is how much reading it would take to
  /// check it by hand.
  final int pages;

  /// Up to three lines it appears in, so one look is enough to decide. Local
  /// only, like the document itself.
  final List<String> examples;

  /// Which rule noticed it.
  final String why;

  const NameCandidate({
    required this.text,
    required this.family,
    required this.occurrences,
    required this.pages,
    required this.examples,
    required this.why,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      family.hashCode ^
      occurrences.hashCode ^
      pages.hashCode ^
      examples.hashCode ^
      why.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NameCandidate &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          family == other.family &&
          occurrences == other.occurrences &&
          pages == other.pages &&
          examples == other.examples &&
          why == other.why;
}

class NameImport {
  final int added;
  final int alreadyKnown;
  final int refused;

  /// One sentence per refused row, in the file's order, so a person can fix
  /// the file rather than guess at it. Never the whole file back.
  final List<String> reasons;

  /// How many **values** the table taught beyond its names — the customer
  /// numbers, contracts and accounts in its other columns.
  ///
  /// Without this `added: 2` meant «two names and six numbers ignored» and
  /// read as success (056).
  final int values;

  /// The header columns this build could not place, by name and in the
  /// file's own order.
  ///
  /// **Nothing is discarded quietly.** A column nobody can name a kind for
  /// stays out of the vault, and the person is told which ones they were so
  /// they can see the difference between «imported» and «imported the
  /// names».
  final List<String> columnsNotUsed;

  const NameImport({
    required this.added,
    required this.alreadyKnown,
    required this.refused,
    required this.reasons,
    required this.values,
    required this.columnsNotUsed,
  });

  @override
  int get hashCode =>
      added.hashCode ^
      alreadyKnown.hashCode ^
      refused.hashCode ^
      reasons.hashCode ^
      values.hashCode ^
      columnsNotUsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NameImport &&
          runtimeType == other.runtimeType &&
          added == other.added &&
          alreadyKnown == other.alreadyKnown &&
          refused == other.refused &&
          reasons == other.reasons &&
          values == other.values &&
          columnsNotUsed == other.columnsNotUsed;
}

@freezed
sealed class NetworkRefusal with _$NetworkRefusal {
  const NetworkRefusal._();

  /// This provider has no credential in this run.
  const factory NetworkRefusal.notConnected() = NetworkRefusal_NotConnected;

  /// The address is not `https`, and is not a machine on this computer.
  const factory NetworkRefusal.insecureUrl() = NetworkRefusal_InsecureUrl;

  /// The host answered with a redirect. We do not follow one: the safe payload
  /// and the credential were addressed to *this* host and go nowhere else.
  const factory NetworkRefusal.redirected({required int status}) =
      NetworkRefusal_Redirected;

  /// The host answered, but not with an answer.
  const factory NetworkRefusal.badStatus({required int status}) =
      NetworkRefusal_BadStatus;

  /// Nothing came back in time.
  const factory NetworkRefusal.timeout({required int millis}) =
      NetworkRefusal_Timeout;

  /// The answer was longer than we accept.
  const factory NetworkRefusal.responseTooLarge({required int limitKib}) =
      NetworkRefusal_ResponseTooLarge;

  /// The outgoing text is longer than this provider accepts. Checked **before**
  /// a socket is opened, so a huge document is refused here rather than turned
  /// into an unreasonable request. (Task 021.)
  const factory NetworkRefusal.payloadTooLarge({
    required int kib,
    required int limitKib,
  }) = NetworkRefusal_PayloadTooLarge;

  /// The answer arrived but is not the shape this provider promised.
  const factory NetworkRefusal.unreadable() = NetworkRefusal_Unreadable;

  /// The host could not be reached at all.
  const factory NetworkRefusal.unreachable() = NetworkRefusal_Unreachable;
}

class PackRow {
  final String id;
  final String label;

  /// `de-DE`, `sv-SE` — the full locale, where this language has a name pack.
  /// Empty where it has label rows only, which English does: a pack is not
  /// required to carry names, and saying so is better than inventing a
  /// locale for a list of words.
  final String locale;

  /// The pack's own version, so a report can say which knowledge produced a
  /// finding.
  final String version;

  /// Rules this language needs that no other language can use, by name.
  ///
  /// The honest measure of the contract. German declares three — a national
  /// vehicle plate, a local telephone number written after the German word
  /// for telephone, a German street line — and Swedish declares none, which
  /// is what «the second language is data» means in a number.
  final List<String> ownRules;

  /// One line naming the sources of its name lists and their licences.
  final String provenance;

  /// How many given and family names it ships with.
  final int given;
  final int family;

  const PackRow({
    required this.id,
    required this.label,
    required this.locale,
    required this.version,
    required this.ownRules,
    required this.provenance,
    required this.given,
    required this.family,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      locale.hashCode ^
      version.hashCode ^
      ownRules.hashCode ^
      provenance.hashCode ^
      given.hashCode ^
      family.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          locale == other.locale &&
          version == other.version &&
          ownRules == other.ownRules &&
          provenance == other.provenance &&
          given == other.given &&
          family == other.family;
}

class PageEdge {
  /// UTF-16 offset of the character the page begins at.
  final int at;

  /// «Page 2» is the first edge a document can have: page one begins at the
  /// top, where no rule is drawn.
  final int page;

  const PageEdge({required this.at, required this.page});

  @override
  int get hashCode => at.hashCode ^ page.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageEdge &&
          runtimeType == other.runtimeType &&
          at == other.at &&
          page == other.page;
}

class PayloadHandle {
  final int id;
  final int session;
  final int revision;

  const PayloadHandle({
    required this.id,
    required this.session,
    required this.revision,
  });

  @override
  int get hashCode => id.hashCode ^ session.hashCode ^ revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PayloadHandle &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          session == other.session &&
          revision == other.revision;
}

class PayloadView {
  final String text;
  final int protectedCount;
  final int openSuggestions;

  /// Where a page begins **in this text**, with the page's own number.
  ///
  /// The Original column can find its own edges: the reader leaves a form
  /// feed between page and page and the column draws where it falls. The
  /// payload cannot — `build` turns each form feed into an ordinary line
  /// break, because a control character is of no use to a model, and one
  /// `\n` is indistinguishable from every other. So the builder says where
  /// they went, and it is the builder that says it because it is the only
  /// place that holds the document's offsets and the payload's at the same
  /// moment. Deriving this afterwards from the protections would be a second
  /// opinion about one fact, which in this project is how two screens come
  /// to disagree.
  ///
  /// Offsets are UTF-16 code units, like every other offset the UI is given.
  /// Adding this changes nothing that leaves the device: it is read off the
  /// payload, never written into it.
  final List<PageEdge> pageEdges;

  const PayloadView({
    required this.text,
    required this.protectedCount,
    required this.openSuggestions,
    required this.pageEdges,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      protectedCount.hashCode ^
      openSuggestions.hashCode ^
      pageEdges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PayloadView &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          protectedCount == other.protectedCount &&
          openSuggestions == other.openSuggestions &&
          pageEdges == other.pageEdges;
}

enum Piece {
  /// The model's own words.
  words,

  /// A value this conversation put back where its token stood.
  restored,

  /// **A token this conversation does not know.**
  ///
  /// It is kept in the view, word for word, because the model really did
  /// write it and removing it would be a second lie. What changes is that it
  /// is no longer indistinguishable from the answer: it says what it is, and
  /// `AnswerSnapshot::unknown_tokens` names every one of them.
  ///
  /// The commonest cause, and the one the owner met: an answer from another
  /// conversation. A token is minted per session today, so Monday's answer
  /// carries names Friday's conversation never made.
  unresolved,
}

class Place {
  final int page;
  final int paragraph;

  const Place({required this.page, required this.paragraph});

  @override
  int get hashCode => page.hashCode ^ paragraph.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Place &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          paragraph == other.paragraph;
}

enum Policy {
  /// Replaced the moment it appears.
  always,

  /// Marked and counted, waiting for your word.
  suggest,

  /// Never found by itself; kept here so its aliases and token stay stable.
  manual,
}

class PrivacyRulesSnapshot {
  final int stateRevision;
  final String? profileId;
  final List<TaughtValueRow> values;
  final List<TaughtExceptionRow> exceptions;

  /// The label rules this person taught, effective for `profile_id`.
  final List<LabelRuleRow> labelRules;

  /// Every rule set this build carries, so the screen can offer them without
  /// keeping a list of its own.
  final List<RuleSetRow> ruleSets;

  /// The sets actually switched on for `profile_id` — what *ran*, not what
  /// was asked for.
  final List<String> activeSets;

  /// Was the «Rules I taught» section built? True since M7.10B; kept as a
  /// field because a screen must read this, never assume it.
  final bool rulesBuilt;

  const PrivacyRulesSnapshot({
    required this.stateRevision,
    this.profileId,
    required this.values,
    required this.exceptions,
    required this.labelRules,
    required this.ruleSets,
    required this.activeSets,
    required this.rulesBuilt,
  });

  @override
  int get hashCode =>
      stateRevision.hashCode ^
      profileId.hashCode ^
      values.hashCode ^
      exceptions.hashCode ^
      labelRules.hashCode ^
      ruleSets.hashCode ^
      activeSets.hashCode ^
      rulesBuilt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrivacyRulesSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          profileId == other.profileId &&
          values == other.values &&
          exceptions == other.exceptions &&
          labelRules == other.labelRules &&
          ruleSets == other.ruleSets &&
          activeSets == other.activeSets &&
          rulesBuilt == other.rulesBuilt;
}

class ProfileRow {
  final String id;
  final String name;

  /// The rule sets switched on for this client's documents. A firm that works
  /// in two languages runs both **in one scan**, so this is a list.
  final List<String> languages;

  const ProfileRow({
    required this.id,
    required this.name,
    required this.languages,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ languages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          languages == other.languages;
}

@freezed
sealed class ProtectOutcome with _$ProtectOutcome {
  const ProtectOutcome._();

  /// Protected here, and in `places` places if all matches were taken.
  const factory ProtectOutcome.applied({
    required String token,
    required int places,
  }) = ProtectOutcome_Applied;

  /// It was already protected; nothing to do but say by whom.
  const factory ProtectOutcome.alreadyProtected({
    required String token,
    required Source source,
    required String sourceDetail,
  }) = ProtectOutcome_AlreadyProtected;

  /// A new spelling of something known: alias of that identity, or a new one?
  const factory ProtectOutcome.belongsToEntity({
    required String entity,
    required String token,
  }) = ProtectOutcome_BelongsToEntity;

  /// The selection cut a protected item; these whole items were taken instead.
  const factory ProtectOutcome.snapped({required List<Span> spans}) =
      ProtectOutcome_Snapped;
}

class ProviderFact {
  final String id;

  /// What Z Privacy speaks, not what a person chose: «OpenAI-compatible».
  /// A **protocol**, shown where the technical detail belongs.
  final String label;

  /// A credential is stored for this provider — not «this provider is set
  /// up». A model on this machine is connected and holds no credential, so
  /// this is `false` while `connected` is `true`, and the two words are not
  /// interchangeable anywhere.
  final bool configured;
  final bool connected;
  final String endpoint;
  final String model;
  final bool credentialRequired;
  final CredentialState credentialState;

  /// Is this endpoint on this computer?
  ///
  /// Reported by the core from the address itself, never worked out by a
  /// screen — because the word «Local» is a promise about where the text
  /// goes, and a promise must be checked by whoever knows. It is the same
  /// test the network door enforces, so the word and the rule cannot part.
  final bool onThisComputer;

  const ProviderFact({
    required this.id,
    required this.label,
    required this.configured,
    required this.connected,
    required this.endpoint,
    required this.model,
    required this.credentialRequired,
    required this.credentialState,
    required this.onThisComputer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      configured.hashCode ^
      connected.hashCode ^
      endpoint.hashCode ^
      model.hashCode ^
      credentialRequired.hashCode ^
      credentialState.hashCode ^
      onThisComputer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderFact &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          configured == other.configured &&
          connected == other.connected &&
          endpoint == other.endpoint &&
          model == other.model &&
          credentialRequired == other.credentialRequired &&
          credentialState == other.credentialState &&
          onThisComputer == other.onThisComputer;
}

class ProviderId {
  final String id;

  const ProviderId({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderId && runtimeType == other.runtimeType && id == other.id;
}

class ProviderRow {
  final String id;
  final String label;

  /// True when this provider can be used at this address in this run.
  final bool connected;

  /// True when that usable connection lives only in memory, because there was
  /// no open vault to seal it into. It is gone when the app closes, and the UI
  /// says so rather than letting the user believe it was saved.
  final bool sessionOnly;

  /// Where requests go. Editable, so a local model on this machine can be used.
  final String baseUrl;

  /// Which model is asked. Not a secret, and shown so the answer can be read
  /// knowing what produced it.
  final String model;

  /// Whether this provider, **at this address**, needs a credential at all.
  ///
  /// A property of the provider, not a rule of the world (the owner, 27 Sep):
  /// a model on this machine needs none, and a future provider may authorise
  /// some other way. A screen asks this instead of assuming.
  final bool credentialRequired;

  const ProviderRow({
    required this.id,
    required this.label,
    required this.connected,
    required this.sessionOnly,
    required this.baseUrl,
    required this.model,
    required this.credentialRequired,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      connected.hashCode ^
      sessionOnly.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      credentialRequired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          connected == other.connected &&
          sessionOnly == other.sessionOnly &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          credentialRequired == other.credentialRequired;
}

class ProviderSnapshot {
  final int stateRevision;
  final List<ProviderFact> providers;

  const ProviderSnapshot({
    required this.stateRevision,
    required this.providers,
  });

  @override
  int get hashCode => stateRevision.hashCode ^ providers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          providers == other.providers;
}

class QuestionView {
  final String text;
  final List<Mark> marks;

  const QuestionView({required this.text, required this.marks});

  @override
  int get hashCode => text.hashCode ^ marks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuestionView &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          marks == other.marks;
}

@freezed
sealed class Refusal with _$Refusal {
  const Refusal._();

  /// Pages with no text layer at all — a photograph of a document. We do not
  /// guess, and we do not send it anywhere to be read.
  const factory Refusal.scannedPdfNoTextLayer({required int pages}) =
      Refusal_ScannedPdfNoTextLayer;

  /// The file is encrypted. Opening it would need its password, which is a
  /// different conversation.
  const factory Refusal.encryptedPdf() = Refusal_EncryptedPdf;

  /// The text is there but this build cannot read it faithfully.
  ///
  /// `page` names where (0 for the file as a whole) and `readable_percent` says
  /// how much of that page came out as text. **Measured per page on purpose:**
  /// nineteen clean pages and one at 41% average out to «fine», and the page
  /// that failed is exactly the page with the client's name on it.
  const factory Refusal.unsupportedEncoding({
    required int page,
    required int readablePercent,
  }) = Refusal_UnsupportedEncoding;

  /// The page's fonts or filters are ones this reader does not understand, so
  /// nothing on it can be trusted — refused even if part of it looks like words.
  /// Fail-closed: the dangerous failure is not a refused import, it is an import
  /// that looks successful while secrets sit in text we could not see.
  const factory Refusal.unreadableStructure({required int page}) =
      Refusal_UnreadableStructure;

  /// The file does not hold together: a broken zip, a truncated PDF.
  const factory Refusal.malformedDocument() = Refusal_MalformedDocument;

  /// Bigger than the limit. A document is untrusted input; one file may not eat
  /// the machine.
  const factory Refusal.documentTooLarge({
    required int mib,
    required int limitMib,
  }) = Refusal_DocumentTooLarge;

  /// More pages than the limit.
  const factory Refusal.tooManyPages({required int pages, required int limit}) =
      Refusal_TooManyPages;

  /// The text after decompression is past the limit — a small file that swells.
  const factory Refusal.textTooLarge({required int limitMib}) =
      Refusal_TextTooLarge;

  /// A few compressed bytes that unpack into a great many: a zip bomb.
  const factory Refusal.compressionBomb({required int ratio}) =
      Refusal_CompressionBomb;

  /// More parts inside the file than a document has any reason to hold.
  const factory Refusal.tooManyParts({required int parts, required int limit}) =
      Refusal_TooManyParts;

  /// Reading it took longer than the limit.
  const factory Refusal.tookTooLong({required int millis}) =
      Refusal_TookTooLong;

  /// Empty, or nothing but whitespace: there is nothing to protect.
  const factory Refusal.emptyDocument() = Refusal_EmptyDocument;
}

@freezed
sealed class ReportSubject with _$ReportSubject {
  const ReportSubject._();

  /// A document that was imported. Every number comes from the core's own
  /// state; the screen passes nothing but the session.
  const factory ReportSubject.imported({required SessionId session}) =
      ReportSubject_Imported;

  /// A file that was not imported. The screen knows these three things and
  /// the core knows nothing about it at all.
  const factory ReportSubject.refused({
    required String name,
    required int bytes,
    required Refusal refusal,
  }) = ReportSubject_Refused;
}

class RescanOutcome {
  final int changedToManual;
  final int revision;

  const RescanOutcome({required this.changedToManual, required this.revision});

  @override
  int get hashCode => changedToManual.hashCode ^ revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RescanOutcome &&
          runtimeType == other.runtimeType &&
          changedToManual == other.changedToManual &&
          revision == other.revision;
}

class RevealState {
  final int? entity;
  final int? valueId;
  final int remainingMs;

  const RevealState({this.entity, this.valueId, required this.remainingMs});

  @override
  int get hashCode => entity.hashCode ^ valueId.hashCode ^ remainingMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RevealState &&
          runtimeType == other.runtimeType &&
          entity == other.entity &&
          valueId == other.valueId &&
          remainingMs == other.remainingMs;
}

class RevealedToken {
  final String token;
  final int remainingMs;

  const RevealedToken({required this.token, required this.remainingMs});

  @override
  int get hashCode => token.hashCode ^ remainingMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RevealedToken &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          remainingMs == other.remainingMs;
}

class RevealedValue {
  final String token;
  final String value;

  /// Every other spelling of the same value. Shown with it because they are
  /// the same secret: a vault screen that listed a name but hid «Herr Müller»
  /// would be keeping something from its owner for no reason.
  final List<String> aliases;
  final int ttlMs;

  const RevealedValue({
    required this.token,
    required this.value,
    required this.aliases,
    required this.ttlMs,
  });

  @override
  int get hashCode =>
      token.hashCode ^ value.hashCode ^ aliases.hashCode ^ ttlMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RevealedValue &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          value == other.value &&
          aliases == other.aliases &&
          ttlMs == other.ttlMs;
}

class Revision {
  final int n;

  const Revision({required this.n});

  @override
  int get hashCode => n.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Revision && runtimeType == other.runtimeType && n == other.n;
}

class RuleSetRow {
  final String id;
  final String label;

  /// How many label rules it carries. Counted, never written down — a number
  /// on a screen must have a source (§2 of the invariants).
  final int rules;

  const RuleSetRow({
    required this.id,
    required this.label,
    required this.rules,
  });

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ rules.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleSetRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          rules == other.rules;
}

enum ScanOrigin { notScanned, onImport, rescan }

class ScanReport {
  final int auto;
  final int suggested;
  final int normal;
  final List<LayerCount> byLayer;

  /// Said out loud, because a locked vault means the app cannot recognise your
  /// own people: the general rules and the pack still run, the vault layer does
  /// not, and the band under the header says so.
  final VaultState vault;

  const ScanReport({
    required this.auto,
    required this.suggested,
    required this.normal,
    required this.byLayer,
    required this.vault,
  });

  @override
  int get hashCode =>
      auto.hashCode ^
      suggested.hashCode ^
      normal.hashCode ^
      byLayer.hashCode ^
      vault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanReport &&
          runtimeType == other.runtimeType &&
          auto == other.auto &&
          suggested == other.suggested &&
          normal == other.normal &&
          byLayer == other.byLayer &&
          vault == other.vault;
}

enum Scope {
  /// This one place, and nothing else.
  once,

  /// Every appearance in this conversation, under one token. Gone when the
  /// conversation is.
  conversation,

  /// Every appearance here, **and kept in the vault under the profile this
  /// conversation is in** — so it is found by itself in that client's next
  /// document, and in no other client's.
  ///
  /// The level a firm with several clients needs: what you learn about one of
  /// them does not become a rule about all of them.
  profile,

  /// Every appearance here, and kept in the vault for **every** profile.
  always,
}

class Segment {
  final String text;
  final Piece piece;

  const Segment({required this.text, required this.piece});

  @override
  int get hashCode => text.hashCode ^ piece.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Segment &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          piece == other.piece;
}

class SelectionView {
  /// Empty when the span holds nothing but space.
  final bool empty;

  /// The pack's guess. `Custom` when nothing recognised it.
  final Kind kind;

  /// How many places this exact value stands in this document, protected or
  /// not. 1 means «all matches» is the same act as «protect», and the button
  /// hides its count.
  final int matches;

  /// The token, when this exact stretch is already protected. Then the only
  /// act offered is Undo.
  final String? protectedAs;
  final Source? protectedBy;

  /// «Z Vault · CLIENT #17», «de:salutation», «selected by you» — the why.
  final String protectedDetail;

  /// The identity the vault knows this value under, when it knows one. Two or
  /// more is a conflict the app must put to the user, never settle itself.
  final List<String> entities;

  /// The whole protected items this selection cuts into. Non-empty means
  /// Protect would snap to these instead of taking the selection as drawn.
  final List<Span> snapsTo;

  /// What Protect will actually take: the selection grown out to whole words
  /// and tidied of the marks at its edges (041-K). The same as the span that
  /// was asked about whenever that one was already whole, and the screen
  /// draws **this** so what is highlighted is what will happen.
  final Span wordSpan;

  /// The capitalised word standing one space before it — «Björn» in front of
  /// «Sandström». An offer the bubble makes and a person answers; the core
  /// never takes it unasked.
  final Span? alsoBefore;

  const SelectionView({
    required this.empty,
    required this.kind,
    required this.matches,
    this.protectedAs,
    this.protectedBy,
    required this.protectedDetail,
    required this.entities,
    required this.snapsTo,
    required this.wordSpan,
    this.alsoBefore,
  });

  @override
  int get hashCode =>
      empty.hashCode ^
      kind.hashCode ^
      matches.hashCode ^
      protectedAs.hashCode ^
      protectedBy.hashCode ^
      protectedDetail.hashCode ^
      entities.hashCode ^
      snapsTo.hashCode ^
      wordSpan.hashCode ^
      alsoBefore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SelectionView &&
          runtimeType == other.runtimeType &&
          empty == other.empty &&
          kind == other.kind &&
          matches == other.matches &&
          protectedAs == other.protectedAs &&
          protectedBy == other.protectedBy &&
          protectedDetail == other.protectedDetail &&
          entities == other.entities &&
          snapsTo == other.snapsTo &&
          wordSpan == other.wordSpan &&
          alsoBefore == other.alsoBefore;
}

class SessionId {
  final int id;

  const SessionId({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionId && runtimeType == other.runtimeType && id == other.id;
}

class Settings {
  /// How much of the Workspace's width the Original column takes, 20 to 80.
  /// A window's preference, kept per device beside the first-run flag, and
  /// readable with no vault — the two columns are drawn long before one.
  final int originalPanePercent;

  /// Do the two columns scroll together? On by default (041-L).
  final bool columnsInStep;

  /// Is the Safe column open? On by default (046/K).
  ///
  /// **The owner's standing rule, 7 October:** «بشرط أن الطوي والفتح لا يتم
  /// تلقائياً، يتم بالضغط على إشارة محددة» — a collapse or an expand is
  /// always a person's press on a visible control, and the app never folds
  /// or unfolds anything by itself. A state nothing but a person may change
  /// has to be remembered, or closing the program would change it for them.
  final bool safeColumnOpen;

  /// Is the side panel at its wider width? Narrow by default, which is the
  /// width it has always had (046/K, the same rule).
  final bool reviewPanelWide;

  /// Scan the moment a document arrives, with no dialog. On by default: the
  /// boards' rule is that nobody has to press anything to be protected.
  final bool scanOnImport;

  /// How long a revealed value stays on screen.
  final int revealSeconds;

  /// Lock the vault after this many minutes of not being used. 0 = never.
  /// Enforced **in the core**, not by a timer in the UI: a screen that forgot
  /// to count would leave the vault open, and nobody would know.
  final int autoLockMinutes;

  /// The detection pack a new session starts with.
  final String packId;

  /// The working language, `en` or `de`.
  ///
  /// **What it selects in v1, exactly:** the language of the First Run page,
  /// and the rule set a new session starts with. It does **not** translate
  /// the interface, which is English. The field is named `ui_language` in the
  /// settings file; that name describes what it will govern, not all it
  /// governs today, and the First Run page says so out loud rather than
  /// letting a person infer a translated app from choosing «Deutsch».
  ///
  /// It is also not «the rule set»: more than one set can run in a scan
  /// (M7.10A), so this picks a starting point, not the only engine allowed.
  final String language;

  /// False until the first-run page has been passed.
  final bool firstRunDone;

  /// True when all of the above will be gone when the app closes, because
  /// there is no vault to keep them in.
  final bool sessionOnly;

  const Settings({
    required this.originalPanePercent,
    required this.columnsInStep,
    required this.safeColumnOpen,
    required this.reviewPanelWide,
    required this.scanOnImport,
    required this.revealSeconds,
    required this.autoLockMinutes,
    required this.packId,
    required this.language,
    required this.firstRunDone,
    required this.sessionOnly,
  });

  @override
  int get hashCode =>
      originalPanePercent.hashCode ^
      columnsInStep.hashCode ^
      safeColumnOpen.hashCode ^
      reviewPanelWide.hashCode ^
      scanOnImport.hashCode ^
      revealSeconds.hashCode ^
      autoLockMinutes.hashCode ^
      packId.hashCode ^
      language.hashCode ^
      firstRunDone.hashCode ^
      sessionOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          originalPanePercent == other.originalPanePercent &&
          columnsInStep == other.columnsInStep &&
          safeColumnOpen == other.safeColumnOpen &&
          reviewPanelWide == other.reviewPanelWide &&
          scanOnImport == other.scanOnImport &&
          revealSeconds == other.revealSeconds &&
          autoLockMinutes == other.autoLockMinutes &&
          packId == other.packId &&
          language == other.language &&
          firstRunDone == other.firstRunDone &&
          sessionOnly == other.sessionOnly;
}

enum Source {
  /// Shapes that need no language: an IBAN, an e-mail, a postcode.
  generalRule,

  /// The habits of one language: Herr, Frau, GmbH, Kundennummer.
  languagePack,

  /// Your own people and things.
  vault,

  /// You selected it.
  hand,
}

class Span {
  final int start;
  final int end;

  const Span({required this.start, required this.end});

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Span &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}

class SwitchOutcome {
  final int keptTokens;
  final int revision;

  const SwitchOutcome({required this.keptTokens, required this.revision});

  @override
  int get hashCode => keptTokens.hashCode ^ revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwitchOutcome &&
          runtimeType == other.runtimeType &&
          keptTokens == other.keptTokens &&
          revision == other.revision;
}

class TaughtExceptionRow {
  final int id;
  final String value;
  final Kind kind;
  final String? profileId;
  final String? profileName;
  final BigInt taughtAt;
  final String why;
  final KnowledgeSource source;

  const TaughtExceptionRow({
    required this.id,
    required this.value,
    required this.kind,
    this.profileId,
    this.profileName,
    required this.taughtAt,
    required this.why,
    required this.source,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      value.hashCode ^
      kind.hashCode ^
      profileId.hashCode ^
      profileName.hashCode ^
      taughtAt.hashCode ^
      why.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaughtExceptionRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          value == other.value &&
          kind == other.kind &&
          profileId == other.profileId &&
          profileName == other.profileName &&
          taughtAt == other.taughtAt &&
          why == other.why &&
          source == other.source;
}

class TaughtNameRow {
  final int id;
  final String text;

  /// A surname, or a given name.
  final bool family;

  /// `None` is everywhere; `Some(profile)` is one client.
  final String? profileId;
  final BigInt learnedAt;

  const TaughtNameRow({
    required this.id,
    required this.text,
    required this.family,
    this.profileId,
    required this.learnedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      text.hashCode ^
      family.hashCode ^
      profileId.hashCode ^
      learnedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaughtNameRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          family == other.family &&
          profileId == other.profileId &&
          learnedAt == other.learnedAt;
}

enum TaughtReach {
  /// The identity holding it belongs to one profile.
  thisProfile,

  /// It belongs to no profile, so every profile knows it.
  everywhere,
}

class TaughtValueRow {
  final int entityId;
  final String entityLabel;
  final int valueId;
  final Kind kind;
  final String? profileId;
  final String? profileName;

  /// How many spellings, not which ones — the same shape as `ValueRow`.
  final int aliases;
  final BigInt taughtAt;
  final String why;
  final KnowledgeSource source;

  const TaughtValueRow({
    required this.entityId,
    required this.entityLabel,
    required this.valueId,
    required this.kind,
    this.profileId,
    this.profileName,
    required this.aliases,
    required this.taughtAt,
    required this.why,
    required this.source,
  });

  @override
  int get hashCode =>
      entityId.hashCode ^
      entityLabel.hashCode ^
      valueId.hashCode ^
      kind.hashCode ^
      profileId.hashCode ^
      profileName.hashCode ^
      aliases.hashCode ^
      taughtAt.hashCode ^
      why.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaughtValueRow &&
          runtimeType == other.runtimeType &&
          entityId == other.entityId &&
          entityLabel == other.entityLabel &&
          valueId == other.valueId &&
          kind == other.kind &&
          profileId == other.profileId &&
          profileName == other.profileName &&
          aliases == other.aliases &&
          taughtAt == other.taughtAt &&
          why == other.why &&
          source == other.source;
}

class TokenRow {
  final String token;
  final Kind kind;
  final Scope scope;
  final Source source;
  final bool decided;
  final String sourceDetail;

  const TokenRow({
    required this.token,
    required this.kind,
    required this.scope,
    required this.source,
    required this.decided,
    required this.sourceDetail,
  });

  @override
  int get hashCode =>
      token.hashCode ^
      kind.hashCode ^
      scope.hashCode ^
      source.hashCode ^
      decided.hashCode ^
      sourceDetail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TokenRow &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          kind == other.kind &&
          scope == other.scope &&
          source == other.source &&
          decided == other.decided &&
          sourceDetail == other.sourceDetail;
}

@freezed
sealed class UndoOutcome with _$UndoOutcome {
  const UndoOutcome._();

  const factory UndoOutcome.nothingToUndo() = UndoOutcome_NothingToUndo;

  /// `created_entity` is set when that act had also added a vault identity.
  const factory UndoOutcome.undone({
    required String token,
    required int places,
    String? createdEntity,
  }) = UndoOutcome_Undone;
}

class UserListRow {
  final String name;

  /// How many **names** are in it: words in the dictionary and whole people
  /// and companies in the vault, which are one thing to the person who
  /// imported them.
  final int names;

  /// How many **other values** are in it — a customer number, a contract, a
  /// phone. A client table teaches these and nothing else does, so they are
  /// counted apart: «21 names» and «21 names and 6 numbers» are different
  /// answers to «what did that file teach me?» (056).
  final int values;

  /// Off means the scanner is not told about them — not that they are gone.
  final bool enabled;

  const UserListRow({
    required this.name,
    required this.names,
    required this.values,
    required this.enabled,
  });

  @override
  int get hashCode =>
      name.hashCode ^ names.hashCode ^ values.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserListRow &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          names == other.names &&
          values == other.values &&
          enabled == other.enabled;
}

enum UserNameKind { given, family, person, company }

class UserNameRow {
  final int id;

  /// The identity this value lives in, when the row is a vault value.
  /// `None` when it is a taught word, and the two ids are not comparable.
  final int? entityId;
  final String text;
  final UserNameKind kind;

  /// Protected the moment it appears, rather than suggested and waiting.
  final bool always;
  final String? profileId;
  final BigInt learnedAt;

  /// Which list it is kept in. A whole person or a company is a value in the
  /// vault rather than a word in a dictionary, and is always in the default
  /// one.
  final String list;

  const UserNameRow({
    required this.id,
    this.entityId,
    required this.text,
    required this.kind,
    required this.always,
    this.profileId,
    required this.learnedAt,
    required this.list,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entityId.hashCode ^
      text.hashCode ^
      kind.hashCode ^
      always.hashCode ^
      profileId.hashCode ^
      learnedAt.hashCode ^
      list.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserNameRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entityId == other.entityId &&
          text == other.text &&
          kind == other.kind &&
          always == other.always &&
          profileId == other.profileId &&
          learnedAt == other.learnedAt &&
          list == other.list;
}

class ValueRow {
  final int id;
  final Kind kind;
  final int aliases;
  final Policy policy;

  const ValueRow({
    required this.id,
    required this.kind,
    required this.aliases,
    required this.policy,
  });

  @override
  int get hashCode =>
      id.hashCode ^ kind.hashCode ^ aliases.hashCode ^ policy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValueRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          aliases == other.aliases &&
          policy == other.policy;
}

class VaultSnapshot {
  final int stateRevision;
  final VaultState vault;
  final int identityCount;
  final int valueCount;
  final List<ProfileRow> profiles;
  final List<TaughtValueRow> taughtValues;
  final bool canForget;

  const VaultSnapshot({
    required this.stateRevision,
    required this.vault,
    required this.identityCount,
    required this.valueCount,
    required this.profiles,
    required this.taughtValues,
    required this.canForget,
  });

  @override
  int get hashCode =>
      stateRevision.hashCode ^
      vault.hashCode ^
      identityCount.hashCode ^
      valueCount.hashCode ^
      profiles.hashCode ^
      taughtValues.hashCode ^
      canForget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          vault == other.vault &&
          identityCount == other.identityCount &&
          valueCount == other.valueCount &&
          profiles == other.profiles &&
          taughtValues == other.taughtValues &&
          canForget == other.canForget;
}

enum VaultState {
  /// There is no vault on this device yet.
  absent,

  /// It exists and is sealed. The vault layer is skipped entirely while it is.
  locked,
  unlocked,
}

@freezed
sealed class VaultUnlockOutcome with _$VaultUnlockOutcome {
  const VaultUnlockOutcome._();

  const factory VaultUnlockOutcome.unlocked({
    required int identities,
    required int values,
  }) = VaultUnlockOutcome_Unlocked;
}

class WorkspaceSnapshot {
  final int stateRevision;
  final SessionId session;
  final String? profileId;
  final int revision;
  final ScanOrigin scanOrigin;
  final int autoProtected;
  final int userProtected;
  final int openSuggestions;
  final int normal;
  final int tokenCount;
  final bool canUndo;
  final List<Finding> findings;
  final DocumentView document;
  final List<TokenRow> tokens;
  final PayloadView? payload;
  final PayloadHandle? handle;
  final VaultState vault;
  final List<AnswerId> answers;

  const WorkspaceSnapshot({
    required this.stateRevision,
    required this.session,
    this.profileId,
    required this.revision,
    required this.scanOrigin,
    required this.autoProtected,
    required this.userProtected,
    required this.openSuggestions,
    required this.normal,
    required this.tokenCount,
    required this.canUndo,
    required this.findings,
    required this.document,
    required this.tokens,
    this.payload,
    this.handle,
    required this.vault,
    required this.answers,
  });

  @override
  int get hashCode =>
      stateRevision.hashCode ^
      session.hashCode ^
      profileId.hashCode ^
      revision.hashCode ^
      scanOrigin.hashCode ^
      autoProtected.hashCode ^
      userProtected.hashCode ^
      openSuggestions.hashCode ^
      normal.hashCode ^
      tokenCount.hashCode ^
      canUndo.hashCode ^
      findings.hashCode ^
      document.hashCode ^
      tokens.hashCode ^
      payload.hashCode ^
      handle.hashCode ^
      vault.hashCode ^
      answers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          session == other.session &&
          profileId == other.profileId &&
          revision == other.revision &&
          scanOrigin == other.scanOrigin &&
          autoProtected == other.autoProtected &&
          userProtected == other.userProtected &&
          openSuggestions == other.openSuggestions &&
          normal == other.normal &&
          tokenCount == other.tokenCount &&
          canUndo == other.canUndo &&
          findings == other.findings &&
          document == other.document &&
          tokens == other.tokens &&
          payload == other.payload &&
          handle == other.handle &&
          vault == other.vault &&
          answers == other.answers;
}
