// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mirrors.freezed.dart';

class AnswerId {
  final int id;

  const AnswerId({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnswerId && runtimeType == other.runtimeType && id == other.id;
}

class AnswerSnapshot {
  final int stateRevision;
  final AnswerId answer;
  final int index;
  final int total;
  final List<Segment> restored;
  final String asWritten;

  const AnswerSnapshot({
    required this.stateRevision,
    required this.answer,
    required this.index,
    required this.total,
    required this.restored,
    required this.asWritten,
  });

  @override
  int get hashCode =>
      stateRevision.hashCode ^
      answer.hashCode ^
      index.hashCode ^
      total.hashCode ^
      restored.hashCode ^
      asWritten.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnswerSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          answer == other.answer &&
          index == other.index &&
          total == other.total &&
          restored == other.restored &&
          asWritten == other.asWritten;
}

@freezed
sealed class ApiError with _$ApiError implements FrbException {
  const ApiError._();

  /// The function exists in the contract but its stage has not been built yet.
  const factory ApiError.notImplemented() = ApiError_NotImplemented;

  /// No such session, or it was closed.
  const factory ApiError.invalidSession() = ApiError_InvalidSession;

  /// No such payload.
  const factory ApiError.invalidHandle() = ApiError_InvalidHandle;

  /// The document changed after this payload was built. Build a new one.
  const factory ApiError.stalePayload({
    required int expected,
    required int got,
  }) = ApiError_StalePayload;

  /// The vault must be opened before this can be answered.
  const factory ApiError.vaultLocked() = ApiError_VaultLocked;

  /// The chosen provider has no key, or is not reachable.
  const factory ApiError.providerUnavailable({required String provider}) =
      ApiError_ProviderUnavailable;

  /// Suggestions are still unanswered; there is no way past them.
  const factory ApiError.openSuggestions({required int count}) =
      ApiError_OpenSuggestions;

  /// A folder, a profile or a pack could not be used, and why.
  const factory ApiError.importRefused({required String reason}) =
      ApiError_ImportRefused;

  /// A document was not imported, with the named reason and a detail for the
  /// user («page 3 of 20 has no text layer»).
  const factory ApiError.documentRefused({
    required Refusal reason,
    required String detail,
  }) = ApiError_DocumentRefused;

  /// A span outside the text, reversed, or inside a character.
  const factory ApiError.badSpan({required String reason}) = ApiError_BadSpan;

  /// No such token in this session.
  const factory ApiError.unknownToken() = ApiError_UnknownToken;

  /// Nothing is protected and nothing is written; there is nothing to build.
  const factory ApiError.nothingToSend() = ApiError_NothingToSend;

  /// The built payload failed the core's own leak audit and was thrown away.
  /// This should never reach a user; if it does, the bug stayed inside.
  const factory ApiError.payloadRefused({required String reason}) =
      ApiError_PayloadRefused;

  /// The network did not carry the question, and why. Never a response body:
  /// a provider's error page can quote the request back, so nothing that comes
  /// off the wire is allowed into this message.
  const factory ApiError.networkRefused({
    required NetworkRefusal reason,
    required String detail,
  }) = ApiError_NetworkRefused;

  /// A vault file asked for KDF costs this build does not support.
  const factory ApiError.unsupportedKdfParameters({required String reason}) =
      ApiError_UnsupportedKdfParameters;

  /// A vault file had bytes after the end of the versioned ZVLT structure.
  const factory ApiError.trailingVaultData() = ApiError_TrailingVaultData;

  /// The vault could not be authenticated after key derivation.
  ///
  /// This does not distinguish a wrong passphrase from a modified vault: the
  /// AEAD tag proves only that opening failed, not which human story caused it.
  const factory ApiError.vaultAuthenticationFailed() =
      ApiError_VaultAuthenticationFailed;

  /// This payload handle already drove a send, or is driving one now.
  const factory ApiError.payloadAlreadySent() = ApiError_PayloadAlreadySent;

  /// The act needs an open vault — Always, Profile, or anything kept for tomorrow —
  /// and there is not one. Named so a press that cannot keep its promise cannot
  /// look like success.
  const factory ApiError.vaultRequired() = ApiError_VaultRequired;
}

enum CredentialState {
  /// No credential is stored for this provider, in the vault or in memory.
  missing,

  /// Kept in process memory for this run only.
  sessionOnly,

  /// Sealed inside the vault.
  encryptedInVault,
}

enum DocumentKind { txt, docx, pdf }

class DocumentView {
  final String text;
  final List<Mark> marks;

  /// What the user called it: a file name, or empty for text typed in.
  final String name;
  final DocumentKind kind;
  final int pages;

  const DocumentView({
    required this.text,
    required this.marks,
    required this.name,
    required this.kind,
    required this.pages,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      marks.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentView &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          marks == other.marks &&
          name == other.name &&
          kind == other.kind &&
          pages == other.pages;
}

class EntityCard {
  final int id;
  final EntityKind kind;
  final String label;
  final String? profileId;
  final List<ValueRow> values;

  const EntityCard({
    required this.id,
    required this.kind,
    required this.label,
    this.profileId,
    required this.values,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      label.hashCode ^
      profileId.hashCode ^
      values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityCard &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          label == other.label &&
          profileId == other.profileId &&
          values == other.values;
}

enum EntityKind { client, person, company, project, custom }

class EntityRow {
  final int id;
  final EntityKind kind;
  final String label;
  final String? profileId;
  final int values;

  /// «4 always · 1 suggest», as the vault list shows it.
  final String policySummary;

  const EntityRow({
    required this.id,
    required this.kind,
    required this.label,
    this.profileId,
    required this.values,
    required this.policySummary,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      label.hashCode ^
      profileId.hashCode ^
      values.hashCode ^
      policySummary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          label == other.label &&
          profileId == other.profileId &&
          values == other.values &&
          policySummary == other.policySummary;
}

class Explanation {
  /// «You taught this value» · «German privacy rule» · «You protected this
  /// by hand» · «A shape that needs no language».
  final String headline;

  /// The particulars, one per line: «Valid IBAN checksum», «German label:
  /// Mobil», «Two rules agree». Empty is not allowed to happen — a protection
  /// with nothing to say about itself is the black box arriving.
  final List<String> because;
  final Kind kind;
  final Scope scope;

  /// Where it applies: «This document only» · «Client Nordstern» · «Everywhere».
  final String applies;

  /// Whether a person decided this, or a layer did.
  final bool decided;
  final String token;

  /// When it was taught, in seconds since 1970. 0 when it was not taught at
  /// all (a rule found it) or when the vault predates the date being kept.
  final BigInt learnedAt;

  /// The identity and value it came from, when the vault taught it. This is
  /// what «Edit» and «Forget» act on.
  final int? entity;
  final int? valueId;

  /// Other spellings of the same value. Shown behind one tap, like every
  /// other value in this app.
  final List<String> aliases;

  const Explanation({
    required this.headline,
    required this.because,
    required this.kind,
    required this.scope,
    required this.applies,
    required this.decided,
    required this.token,
    required this.learnedAt,
    this.entity,
    this.valueId,
    required this.aliases,
  });

  @override
  int get hashCode =>
      headline.hashCode ^
      because.hashCode ^
      kind.hashCode ^
      scope.hashCode ^
      applies.hashCode ^
      decided.hashCode ^
      token.hashCode ^
      learnedAt.hashCode ^
      entity.hashCode ^
      valueId.hashCode ^
      aliases.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Explanation &&
          runtimeType == other.runtimeType &&
          headline == other.headline &&
          because == other.because &&
          kind == other.kind &&
          scope == other.scope &&
          applies == other.applies &&
          decided == other.decided &&
          token == other.token &&
          learnedAt == other.learnedAt &&
          entity == other.entity &&
          valueId == other.valueId &&
          aliases == other.aliases;
}

class Finding {
  final int id;
  final Span span;
  final Kind kind;

  /// Who found it.
  final Source source;

  /// Whether a person decided it. The review list groups by this, not by
  /// `source`: confirming the pack's suggestion is **your** decision.
  final bool decided;
  final String reason;
  final MarkState state;

  /// The vault identities that claim this text.
  ///
  /// Empty when no identity is involved; one when the vault knows it; **more
  /// than one is a conflict** — two identities claim the same spelling, and the
  /// scanner refuses to choose silently. The app must ask.
  final List<String> entities;

  /// Where it sits: page and paragraph. Kept through protection, so a review
  /// list can still jump to page 17 after everything is replaced.
  final Place? place;

  const Finding({
    required this.id,
    required this.span,
    required this.kind,
    required this.source,
    required this.decided,
    required this.reason,
    required this.state,
    required this.entities,
    this.place,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      span.hashCode ^
      kind.hashCode ^
      source.hashCode ^
      decided.hashCode ^
      reason.hashCode ^
      state.hashCode ^
      entities.hashCode ^
      place.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Finding &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          span == other.span &&
          kind == other.kind &&
          source == other.source &&
          decided == other.decided &&
          reason == other.reason &&
          state == other.state &&
          entities == other.entities &&
          place == other.place;
}

enum FindingAnswer { protect, always, notSensitive, skip }

class ForgetPlan {
  /// What it is, so the sheet can name it back to the user.
  final String what;
  final int values;
  final int aliases;

  /// Identities that would be left holding nothing, and so go too.
  final int identities;

  /// The profiles it is associated with, by name.
  final List<String> profiles;

  /// What is **not** touched, said out loud because the user is about to
  /// press a button that says «forget».
  final List<String> keeps;

  /// Permanent knowledge that could recognise this value **in future**.
  ///
  /// The definition is strict on purpose (the owner, 28 Sep). Empty means:
  /// *nothing kept on this device will recognise this value again.* It does
  /// **not** mean the value is nowhere in the program — the open
  /// conversation's token store still holds it, and an answer already
  /// received still reads as it did. Those are not knowledge for tomorrow;
  /// they are today's work, and `keeps` says so in words.
  ///
  /// Must be empty after forgetting. Reported rather than assumed, and both a
  /// test and the screen check it.
  final List<String> stillKnownBy;

  const ForgetPlan({
    required this.what,
    required this.values,
    required this.aliases,
    required this.identities,
    required this.profiles,
    required this.keeps,
    required this.stillKnownBy,
  });

  @override
  int get hashCode =>
      what.hashCode ^
      values.hashCode ^
      aliases.hashCode ^
      identities.hashCode ^
      profiles.hashCode ^
      keeps.hashCode ^
      stillKnownBy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForgetPlan &&
          runtimeType == other.runtimeType &&
          what == other.what &&
          values == other.values &&
          aliases == other.aliases &&
          identities == other.identities &&
          profiles == other.profiles &&
          keeps == other.keeps &&
          stillKnownBy == other.stillKnownBy;
}

class HomeSnapshot {
  final int stateRevision;
  final VaultState vault;
  final int identityCount;
  final int valueCount;
  final List<ProfileRow> profiles;
  final List<PackRow> packs;
  final List<ProviderFact> providers;
  final Settings settings;
  final List<KindRow> kinds;

  const HomeSnapshot({
    required this.stateRevision,
    required this.vault,
    required this.identityCount,
    required this.valueCount,
    required this.profiles,
    required this.packs,
    required this.providers,
    required this.settings,
    required this.kinds,
  });

  @override
  int get hashCode =>
      stateRevision.hashCode ^
      vault.hashCode ^
      identityCount.hashCode ^
      valueCount.hashCode ^
      profiles.hashCode ^
      packs.hashCode ^
      providers.hashCode ^
      settings.hashCode ^
      kinds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          vault == other.vault &&
          identityCount == other.identityCount &&
          valueCount == other.valueCount &&
          profiles == other.profiles &&
          packs == other.packs &&
          providers == other.providers &&
          settings == other.settings &&
          kinds == other.kinds;
}

enum Kind {
  person,
  company,
  email,
  phone,

  /// An IBAN — an account, internationally addressed.
  iban,

  /// A bank's own identifier (SWIFT/BIC). Not an IBAN, and not the same secret.
  bic,

  /// A plain account number, as a German letter writes it after «Kontonummer:».
  account,
  taxId,
  customerNo,
  address,
  contract,
  project,
  client,
  custom,
}

class KindRow {
  final Kind kind;

  /// What to call it. The core's word, not the screen's.
  final String label;

  /// True for a kind the user made. Always false today; the field exists so
  /// that the day it is true, nothing above it needs rewriting.
  final bool custom;

  const KindRow({
    required this.kind,
    required this.label,
    required this.custom,
  });

  @override
  int get hashCode => kind.hashCode ^ label.hashCode ^ custom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KindRow &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          label == other.label &&
          custom == other.custom;
}

enum KnowledgeSource { builtIn, userTaughtValue, userException }

class LayerCount {
  final Source source;
  final String detail;
  final int count;

  const LayerCount({
    required this.source,
    required this.detail,
    required this.count,
  });

  @override
  int get hashCode => source.hashCode ^ detail.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayerCount &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          detail == other.detail &&
          count == other.count;
}

class Mark {
  final Span span;
  final MarkState state;
  final String? token;
  final Kind kind;

  /// Who **found** it.
  final Source source;

  /// Whether a person **decided** it, as against a layer deciding on its own.
  ///
  /// Two different questions, and mixing them wrote a false history: the pack
  /// may have found a name while you chose to protect it, and a list that
  /// said «you found this» would be wrong. It is also a rule and not only a
  /// label — see [`Scope`] and the rescan behaviour. (Task 033/034.)
  final bool decided;

  /// Pack id, entity id, or the rule's name — the "why" behind the mark.
  final String sourceDetail;

  /// The page and paragraph it sits on, when the text came from a document.
  final Place? place;

  const Mark({
    required this.span,
    required this.state,
    this.token,
    required this.kind,
    required this.source,
    required this.decided,
    required this.sourceDetail,
    this.place,
  });

  @override
  int get hashCode =>
      span.hashCode ^
      state.hashCode ^
      token.hashCode ^
      kind.hashCode ^
      source.hashCode ^
      decided.hashCode ^
      sourceDetail.hashCode ^
      place.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Mark &&
          runtimeType == other.runtimeType &&
          span == other.span &&
          state == other.state &&
          token == other.token &&
          kind == other.kind &&
          source == other.source &&
          decided == other.decided &&
          sourceDetail == other.sourceDetail &&
          place == other.place;
}

enum MarkState { protected, suggested }

@freezed
sealed class NetworkRefusal with _$NetworkRefusal {
  const NetworkRefusal._();

  /// This provider has no credential in this run.
  const factory NetworkRefusal.notConnected() = NetworkRefusal_NotConnected;

  /// The address is not `https`, and is not a machine on this computer.
  const factory NetworkRefusal.insecureUrl() = NetworkRefusal_InsecureUrl;

  /// The host answered with a redirect. We do not follow one: the safe payload
  /// and the credential were addressed to *this* host and go nowhere else.
  const factory NetworkRefusal.redirected({required int status}) =
      NetworkRefusal_Redirected;

  /// The host answered, but not with an answer.
  const factory NetworkRefusal.badStatus({required int status}) =
      NetworkRefusal_BadStatus;

  /// Nothing came back in time.
  const factory NetworkRefusal.timeout({required int millis}) =
      NetworkRefusal_Timeout;

  /// The answer was longer than we accept.
  const factory NetworkRefusal.responseTooLarge({required int limitKib}) =
      NetworkRefusal_ResponseTooLarge;

  /// The outgoing text is longer than this provider accepts. Checked **before**
  /// a socket is opened, so a huge document is refused here rather than turned
  /// into an unreasonable request. (Task 021.)
  const factory NetworkRefusal.payloadTooLarge({
    required int kib,
    required int limitKib,
  }) = NetworkRefusal_PayloadTooLarge;

  /// The answer arrived but is not the shape this provider promised.
  const factory NetworkRefusal.unreadable() = NetworkRefusal_Unreadable;

  /// The host could not be reached at all.
  const factory NetworkRefusal.unreachable() = NetworkRefusal_Unreachable;
}

class PackRow {
  final String id;
  final String label;

  const PackRow({required this.id, required this.label});

  @override
  int get hashCode => id.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label;
}

class PayloadHandle {
  final int id;
  final int session;
  final int revision;

  const PayloadHandle({
    required this.id,
    required this.session,
    required this.revision,
  });

  @override
  int get hashCode => id.hashCode ^ session.hashCode ^ revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PayloadHandle &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          session == other.session &&
          revision == other.revision;
}

class PayloadView {
  final String text;
  final int protectedCount;
  final int openSuggestions;

  const PayloadView({
    required this.text,
    required this.protectedCount,
    required this.openSuggestions,
  });

  @override
  int get hashCode =>
      text.hashCode ^ protectedCount.hashCode ^ openSuggestions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PayloadView &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          protectedCount == other.protectedCount &&
          openSuggestions == other.openSuggestions;
}

class Place {
  final int page;
  final int paragraph;

  const Place({required this.page, required this.paragraph});

  @override
  int get hashCode => page.hashCode ^ paragraph.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Place &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          paragraph == other.paragraph;
}

enum Policy {
  /// Replaced the moment it appears.
  always,

  /// Marked and counted, waiting for your word.
  suggest,

  /// Never found by itself; kept here so its aliases and token stay stable.
  manual,
}

class PrivacyRulesSnapshot {
  final int stateRevision;
  final String? profileId;
  final List<TaughtValueRow> values;
  final List<TaughtExceptionRow> exceptions;

  /// Phase A names this section honestly, but does not pretend it exists.
  final bool rulesBuilt;

  const PrivacyRulesSnapshot({
    required this.stateRevision,
    this.profileId,
    required this.values,
    required this.exceptions,
    required this.rulesBuilt,
  });

  @override
  int get hashCode =>
      stateRevision.hashCode ^
      profileId.hashCode ^
      values.hashCode ^
      exceptions.hashCode ^
      rulesBuilt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrivacyRulesSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          profileId == other.profileId &&
          values == other.values &&
          exceptions == other.exceptions &&
          rulesBuilt == other.rulesBuilt;
}

class ProfileRow {
  final String id;
  final String name;

  const ProfileRow({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

@freezed
sealed class ProtectOutcome with _$ProtectOutcome {
  const ProtectOutcome._();

  /// Protected here, and in `places` places if all matches were taken.
  const factory ProtectOutcome.applied({
    required String token,
    required int places,
  }) = ProtectOutcome_Applied;

  /// It was already protected; nothing to do but say by whom.
  const factory ProtectOutcome.alreadyProtected({
    required String token,
    required Source source,
    required String sourceDetail,
  }) = ProtectOutcome_AlreadyProtected;

  /// A new spelling of something known: alias of that identity, or a new one?
  const factory ProtectOutcome.belongsToEntity({
    required String entity,
    required String token,
  }) = ProtectOutcome_BelongsToEntity;

  /// The selection cut a protected item; these whole items were taken instead.
  const factory ProtectOutcome.snapped({required List<Span> spans}) =
      ProtectOutcome_Snapped;
}

class ProviderFact {
  final String id;
  final String label;
  final bool configured;
  final bool connected;
  final String endpoint;
  final String model;
  final bool credentialRequired;
  final CredentialState credentialState;

  const ProviderFact({
    required this.id,
    required this.label,
    required this.configured,
    required this.connected,
    required this.endpoint,
    required this.model,
    required this.credentialRequired,
    required this.credentialState,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      configured.hashCode ^
      connected.hashCode ^
      endpoint.hashCode ^
      model.hashCode ^
      credentialRequired.hashCode ^
      credentialState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderFact &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          configured == other.configured &&
          connected == other.connected &&
          endpoint == other.endpoint &&
          model == other.model &&
          credentialRequired == other.credentialRequired &&
          credentialState == other.credentialState;
}

class ProviderId {
  final String id;

  const ProviderId({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderId && runtimeType == other.runtimeType && id == other.id;
}

class ProviderRow {
  final String id;
  final String label;

  /// True when this provider can be used at this address in this run.
  final bool connected;

  /// True when that usable connection lives only in memory, because there was
  /// no open vault to seal it into. It is gone when the app closes, and the UI
  /// says so rather than letting the user believe it was saved.
  final bool sessionOnly;

  /// Where requests go. Editable, so a local model on this machine can be used.
  final String baseUrl;

  /// Which model is asked. Not a secret, and shown so the answer can be read
  /// knowing what produced it.
  final String model;

  /// Whether this provider, **at this address**, needs a credential at all.
  ///
  /// A property of the provider, not a rule of the world (the owner, 27 Sep):
  /// a model on this machine needs none, and a future provider may authorise
  /// some other way. A screen asks this instead of assuming.
  final bool credentialRequired;

  const ProviderRow({
    required this.id,
    required this.label,
    required this.connected,
    required this.sessionOnly,
    required this.baseUrl,
    required this.model,
    required this.credentialRequired,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      connected.hashCode ^
      sessionOnly.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      credentialRequired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          connected == other.connected &&
          sessionOnly == other.sessionOnly &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          credentialRequired == other.credentialRequired;
}

class ProviderSnapshot {
  final int stateRevision;
  final List<ProviderFact> providers;

  const ProviderSnapshot({
    required this.stateRevision,
    required this.providers,
  });

  @override
  int get hashCode => stateRevision.hashCode ^ providers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          providers == other.providers;
}

@freezed
sealed class Refusal with _$Refusal {
  const Refusal._();

  /// Pages with no text layer at all — a photograph of a document. We do not
  /// guess, and we do not send it anywhere to be read.
  const factory Refusal.scannedPdfNoTextLayer({required int pages}) =
      Refusal_ScannedPdfNoTextLayer;

  /// The file is encrypted. Opening it would need its password, which is a
  /// different conversation.
  const factory Refusal.encryptedPdf() = Refusal_EncryptedPdf;

  /// The text is there but this build cannot read it faithfully.
  ///
  /// `page` names where (0 for the file as a whole) and `readable_percent` says
  /// how much of that page came out as text. **Measured per page on purpose:**
  /// nineteen clean pages and one at 41% average out to «fine», and the page
  /// that failed is exactly the page with the client's name on it.
  const factory Refusal.unsupportedEncoding({
    required int page,
    required int readablePercent,
  }) = Refusal_UnsupportedEncoding;

  /// The page's fonts or filters are ones this reader does not understand, so
  /// nothing on it can be trusted — refused even if part of it looks like words.
  /// Fail-closed: the dangerous failure is not a refused import, it is an import
  /// that looks successful while secrets sit in text we could not see.
  const factory Refusal.unreadableStructure({required int page}) =
      Refusal_UnreadableStructure;

  /// The file does not hold together: a broken zip, a truncated PDF.
  const factory Refusal.malformedDocument() = Refusal_MalformedDocument;

  /// Bigger than the limit. A document is untrusted input; one file may not eat
  /// the machine.
  const factory Refusal.documentTooLarge({
    required int mib,
    required int limitMib,
  }) = Refusal_DocumentTooLarge;

  /// More pages than the limit.
  const factory Refusal.tooManyPages({required int pages, required int limit}) =
      Refusal_TooManyPages;

  /// The text after decompression is past the limit — a small file that swells.
  const factory Refusal.textTooLarge({required int limitMib}) =
      Refusal_TextTooLarge;

  /// A few compressed bytes that unpack into a great many: a zip bomb.
  const factory Refusal.compressionBomb({required int ratio}) =
      Refusal_CompressionBomb;

  /// More parts inside the file than a document has any reason to hold.
  const factory Refusal.tooManyParts({required int parts, required int limit}) =
      Refusal_TooManyParts;

  /// Reading it took longer than the limit.
  const factory Refusal.tookTooLong({required int millis}) =
      Refusal_TookTooLong;

  /// Empty, or nothing but whitespace: there is nothing to protect.
  const factory Refusal.emptyDocument() = Refusal_EmptyDocument;
}

class RescanOutcome {
  final int changedToManual;
  final int revision;

  const RescanOutcome({required this.changedToManual, required this.revision});

  @override
  int get hashCode => changedToManual.hashCode ^ revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RescanOutcome &&
          runtimeType == other.runtimeType &&
          changedToManual == other.changedToManual &&
          revision == other.revision;
}

class RevealedValue {
  final String token;
  final String value;

  /// Every other spelling of the same value. Shown with it because they are
  /// the same secret: a vault screen that listed a name but hid «Herr Müller»
  /// would be keeping something from its owner for no reason.
  final List<String> aliases;
  final int ttlMs;

  const RevealedValue({
    required this.token,
    required this.value,
    required this.aliases,
    required this.ttlMs,
  });

  @override
  int get hashCode =>
      token.hashCode ^ value.hashCode ^ aliases.hashCode ^ ttlMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RevealedValue &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          value == other.value &&
          aliases == other.aliases &&
          ttlMs == other.ttlMs;
}

class Revision {
  final int n;

  const Revision({required this.n});

  @override
  int get hashCode => n.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Revision && runtimeType == other.runtimeType && n == other.n;
}

enum ScanOrigin { notScanned, onImport, rescan }

class ScanReport {
  final int auto;
  final int suggested;
  final int normal;
  final List<LayerCount> byLayer;

  /// Said out loud, because a locked vault means the app cannot recognise your
  /// own people: the general rules and the pack still run, the vault layer does
  /// not, and the band under the header says so.
  final VaultState vault;

  const ScanReport({
    required this.auto,
    required this.suggested,
    required this.normal,
    required this.byLayer,
    required this.vault,
  });

  @override
  int get hashCode =>
      auto.hashCode ^
      suggested.hashCode ^
      normal.hashCode ^
      byLayer.hashCode ^
      vault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanReport &&
          runtimeType == other.runtimeType &&
          auto == other.auto &&
          suggested == other.suggested &&
          normal == other.normal &&
          byLayer == other.byLayer &&
          vault == other.vault;
}

enum Scope {
  /// This one place, and nothing else.
  once,

  /// Every appearance in this conversation, under one token. Gone when the
  /// conversation is.
  conversation,

  /// Every appearance here, **and kept in the vault under the profile this
  /// conversation is in** — so it is found by itself in that client's next
  /// document, and in no other client's.
  ///
  /// The level a firm with several clients needs: what you learn about one of
  /// them does not become a rule about all of them.
  profile,

  /// Every appearance here, and kept in the vault for **every** profile.
  always,
}

class Segment {
  final String text;
  final bool restored;

  const Segment({required this.text, required this.restored});

  @override
  int get hashCode => text.hashCode ^ restored.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Segment &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          restored == other.restored;
}

class SelectionView {
  /// Empty when the span holds nothing but space.
  final bool empty;

  /// The pack's guess. `Custom` when nothing recognised it.
  final Kind kind;

  /// How many places this exact value stands in this document, protected or
  /// not. 1 means «all matches» is the same act as «protect», and the button
  /// hides its count.
  final int matches;

  /// The token, when this exact stretch is already protected. Then the only
  /// act offered is Undo.
  final String? protectedAs;
  final Source? protectedBy;

  /// «Z Vault · CLIENT #17», «de:salutation», «selected by you» — the why.
  final String protectedDetail;

  /// The identity the vault knows this value under, when it knows one. Two or
  /// more is a conflict the app must put to the user, never settle itself.
  final List<String> entities;

  /// The whole protected items this selection cuts into. Non-empty means
  /// Protect would snap to these instead of taking the selection as drawn.
  final List<Span> snapsTo;

  const SelectionView({
    required this.empty,
    required this.kind,
    required this.matches,
    this.protectedAs,
    this.protectedBy,
    required this.protectedDetail,
    required this.entities,
    required this.snapsTo,
  });

  @override
  int get hashCode =>
      empty.hashCode ^
      kind.hashCode ^
      matches.hashCode ^
      protectedAs.hashCode ^
      protectedBy.hashCode ^
      protectedDetail.hashCode ^
      entities.hashCode ^
      snapsTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SelectionView &&
          runtimeType == other.runtimeType &&
          empty == other.empty &&
          kind == other.kind &&
          matches == other.matches &&
          protectedAs == other.protectedAs &&
          protectedBy == other.protectedBy &&
          protectedDetail == other.protectedDetail &&
          entities == other.entities &&
          snapsTo == other.snapsTo;
}

class SessionId {
  final int id;

  const SessionId({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionId && runtimeType == other.runtimeType && id == other.id;
}

class Settings {
  /// Scan the moment a document arrives, with no dialog. On by default: the
  /// boards' rule is that nobody has to press anything to be protected.
  final bool scanOnImport;

  /// How long a revealed value stays on screen.
  final int revealSeconds;

  /// Lock the vault after this many minutes of not being used. 0 = never.
  /// Enforced **in the core**, not by a timer in the UI: a screen that forgot
  /// to count would leave the vault open, and nobody would know.
  final int autoLockMinutes;

  /// The detection pack a new session starts with.
  final String packId;

  /// The working language, `en` or `de`. It picks the pack today; the
  /// interface follows when it is translated.
  final String language;

  /// False until the first-run page has been passed.
  final bool firstRunDone;

  /// True when all of the above will be gone when the app closes, because
  /// there is no vault to keep them in.
  final bool sessionOnly;

  const Settings({
    required this.scanOnImport,
    required this.revealSeconds,
    required this.autoLockMinutes,
    required this.packId,
    required this.language,
    required this.firstRunDone,
    required this.sessionOnly,
  });

  @override
  int get hashCode =>
      scanOnImport.hashCode ^
      revealSeconds.hashCode ^
      autoLockMinutes.hashCode ^
      packId.hashCode ^
      language.hashCode ^
      firstRunDone.hashCode ^
      sessionOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          scanOnImport == other.scanOnImport &&
          revealSeconds == other.revealSeconds &&
          autoLockMinutes == other.autoLockMinutes &&
          packId == other.packId &&
          language == other.language &&
          firstRunDone == other.firstRunDone &&
          sessionOnly == other.sessionOnly;
}

enum Source {
  /// Shapes that need no language: an IBAN, an e-mail, a postcode.
  generalRule,

  /// The habits of one language: Herr, Frau, GmbH, Kundennummer.
  languagePack,

  /// Your own people and things.
  vault,

  /// You selected it.
  hand,
}

class Span {
  final int start;
  final int end;

  const Span({required this.start, required this.end});

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Span &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}

class SwitchOutcome {
  final int keptTokens;
  final int revision;

  const SwitchOutcome({required this.keptTokens, required this.revision});

  @override
  int get hashCode => keptTokens.hashCode ^ revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwitchOutcome &&
          runtimeType == other.runtimeType &&
          keptTokens == other.keptTokens &&
          revision == other.revision;
}

class TaughtExceptionRow {
  final int id;
  final String value;
  final Kind kind;
  final String? profileId;
  final String? profileName;
  final BigInt taughtAt;
  final String why;
  final KnowledgeSource source;

  const TaughtExceptionRow({
    required this.id,
    required this.value,
    required this.kind,
    this.profileId,
    this.profileName,
    required this.taughtAt,
    required this.why,
    required this.source,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      value.hashCode ^
      kind.hashCode ^
      profileId.hashCode ^
      profileName.hashCode ^
      taughtAt.hashCode ^
      why.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaughtExceptionRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          value == other.value &&
          kind == other.kind &&
          profileId == other.profileId &&
          profileName == other.profileName &&
          taughtAt == other.taughtAt &&
          why == other.why &&
          source == other.source;
}

class TaughtValueRow {
  final int entityId;
  final String entityLabel;
  final int valueId;
  final String value;
  final Kind kind;
  final String? profileId;
  final String? profileName;
  final List<String> aliases;
  final BigInt taughtAt;
  final String why;
  final KnowledgeSource source;

  const TaughtValueRow({
    required this.entityId,
    required this.entityLabel,
    required this.valueId,
    required this.value,
    required this.kind,
    this.profileId,
    this.profileName,
    required this.aliases,
    required this.taughtAt,
    required this.why,
    required this.source,
  });

  @override
  int get hashCode =>
      entityId.hashCode ^
      entityLabel.hashCode ^
      valueId.hashCode ^
      value.hashCode ^
      kind.hashCode ^
      profileId.hashCode ^
      profileName.hashCode ^
      aliases.hashCode ^
      taughtAt.hashCode ^
      why.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaughtValueRow &&
          runtimeType == other.runtimeType &&
          entityId == other.entityId &&
          entityLabel == other.entityLabel &&
          valueId == other.valueId &&
          value == other.value &&
          kind == other.kind &&
          profileId == other.profileId &&
          profileName == other.profileName &&
          aliases == other.aliases &&
          taughtAt == other.taughtAt &&
          why == other.why &&
          source == other.source;
}

class TokenRow {
  final String token;
  final Kind kind;
  final Scope scope;
  final Source source;
  final bool decided;
  final String sourceDetail;

  const TokenRow({
    required this.token,
    required this.kind,
    required this.scope,
    required this.source,
    required this.decided,
    required this.sourceDetail,
  });

  @override
  int get hashCode =>
      token.hashCode ^
      kind.hashCode ^
      scope.hashCode ^
      source.hashCode ^
      decided.hashCode ^
      sourceDetail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TokenRow &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          kind == other.kind &&
          scope == other.scope &&
          source == other.source &&
          decided == other.decided &&
          sourceDetail == other.sourceDetail;
}

@freezed
sealed class UndoOutcome with _$UndoOutcome {
  const UndoOutcome._();

  const factory UndoOutcome.nothingToUndo() = UndoOutcome_NothingToUndo;

  /// `created_entity` is set when that act had also added a vault identity.
  const factory UndoOutcome.undone({
    required String token,
    required int places,
    String? createdEntity,
  }) = UndoOutcome_Undone;
}

class ValueRow {
  final int id;
  final Kind kind;
  final int aliases;
  final Policy policy;

  const ValueRow({
    required this.id,
    required this.kind,
    required this.aliases,
    required this.policy,
  });

  @override
  int get hashCode =>
      id.hashCode ^ kind.hashCode ^ aliases.hashCode ^ policy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValueRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          aliases == other.aliases &&
          policy == other.policy;
}

class VaultSnapshot {
  final int stateRevision;
  final VaultState vault;
  final int identityCount;
  final int valueCount;
  final List<ProfileRow> profiles;
  final List<TaughtValueRow> taughtValues;
  final bool canForget;

  const VaultSnapshot({
    required this.stateRevision,
    required this.vault,
    required this.identityCount,
    required this.valueCount,
    required this.profiles,
    required this.taughtValues,
    required this.canForget,
  });

  @override
  int get hashCode =>
      stateRevision.hashCode ^
      vault.hashCode ^
      identityCount.hashCode ^
      valueCount.hashCode ^
      profiles.hashCode ^
      taughtValues.hashCode ^
      canForget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          vault == other.vault &&
          identityCount == other.identityCount &&
          valueCount == other.valueCount &&
          profiles == other.profiles &&
          taughtValues == other.taughtValues &&
          canForget == other.canForget;
}

enum VaultState {
  /// There is no vault on this device yet.
  absent,

  /// It exists and is sealed. The vault layer is skipped entirely while it is.
  locked,
  unlocked,
}

@freezed
sealed class VaultUnlockOutcome with _$VaultUnlockOutcome {
  const VaultUnlockOutcome._();

  const factory VaultUnlockOutcome.unlocked({
    required int identities,
    required int values,
  }) = VaultUnlockOutcome_Unlocked;
}

class WorkspaceSnapshot {
  final int stateRevision;
  final SessionId session;
  final String? profileId;
  final int revision;
  final ScanOrigin scanOrigin;
  final int autoProtected;
  final int userProtected;
  final int openSuggestions;
  final int normal;
  final int tokenCount;
  final bool canUndo;
  final List<Finding> findings;
  final DocumentView document;
  final List<TokenRow> tokens;
  final PayloadView? payload;
  final PayloadHandle? handle;
  final VaultState vault;
  final List<AnswerId> answers;

  const WorkspaceSnapshot({
    required this.stateRevision,
    required this.session,
    this.profileId,
    required this.revision,
    required this.scanOrigin,
    required this.autoProtected,
    required this.userProtected,
    required this.openSuggestions,
    required this.normal,
    required this.tokenCount,
    required this.canUndo,
    required this.findings,
    required this.document,
    required this.tokens,
    this.payload,
    this.handle,
    required this.vault,
    required this.answers,
  });

  @override
  int get hashCode =>
      stateRevision.hashCode ^
      session.hashCode ^
      profileId.hashCode ^
      revision.hashCode ^
      scanOrigin.hashCode ^
      autoProtected.hashCode ^
      userProtected.hashCode ^
      openSuggestions.hashCode ^
      normal.hashCode ^
      tokenCount.hashCode ^
      canUndo.hashCode ^
      findings.hashCode ^
      document.hashCode ^
      tokens.hashCode ^
      payload.hashCode ^
      handle.hashCode ^
      vault.hashCode ^
      answers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceSnapshot &&
          runtimeType == other.runtimeType &&
          stateRevision == other.stateRevision &&
          session == other.session &&
          profileId == other.profileId &&
          revision == other.revision &&
          scanOrigin == other.scanOrigin &&
          autoProtected == other.autoProtected &&
          userProtected == other.userProtected &&
          openSuggestions == other.openSuggestions &&
          normal == other.normal &&
          tokenCount == other.tokenCount &&
          canUndo == other.canUndo &&
          findings == other.findings &&
          document == other.document &&
          tokens == other.tokens &&
          payload == other.payload &&
          handle == other.handle &&
          vault == other.vault &&
          answers == other.answers;
}
