#!/usr/bin/env python3
"""Generate the bridge's mirror declarations from the one contract file.

flutter_rust_bridge treats types from another crate as opaque unless it is told
their shape. Writing those shapes by hand would mean two sources of truth and
silent drift the day someone adds a field. So they are generated from
`z_core/src/api.rs`, and gate G12 fails the build if the generated file on disk
is not what this script would write today.

Usage:
    python3 scripts/gen_mirrors.py            # write the file
    python3 scripts/gen_mirrors.py --check    # exit 1 if it is out of date
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "z_core" / "src" / "api.rs"
MIRRORS = ROOT / "bridges" / "native" / "z_bridge" / "src" / "api" / "mirrors.rs"

HEAD = """// GENERATED by scripts/gen_mirrors.py — do not edit by hand.
//
// One shape declaration per public type of `z_core::api`, so that Dart gets a
// real class for each instead of an opaque handle. Without these, the UI could
// not read why a Protect was refused, or which case an outcome is.
//
// Gate G12 regenerates this file and fails the build if it differs.
#![allow(dead_code)]

use flutter_rust_bridge::frb;
// Re-exported: the generated bridge code refers to these by path.
pub use z_core::api::*;

"""

# `pub struct Name {` / `pub enum Name {` at column zero, body until a closing
# brace at column zero. The contract file is written in exactly this style, and
# G11 keeps it that way.
BLOCK = re.compile(
    r"^pub (?P<what>struct|enum) (?P<name>[A-Za-z_][A-Za-z0-9_]*) \{\n(?P<body>.*?)^\}\n",
    re.MULTILINE | re.DOTALL,
)


def render(source: str) -> str:
    out = [HEAD]
    for m in BLOCK.finditer(source):
        what, name, body = m.group("what"), m.group("name"), m.group("body")
        out.append(f"#[frb(mirror({name}))]\npub {what} _{name} {{\n{body}}}\n\n")
    return "".join(out)


def main() -> int:
    wanted = render(CONTRACT.read_text())
    if "--check" in sys.argv:
        have = MIRRORS.read_text() if MIRRORS.exists() else ""
        if have != wanted:
            print(f"{MIRRORS} is out of date — run: python3 scripts/gen_mirrors.py")
            return 1
        return 0
    MIRRORS.parent.mkdir(parents=True, exist_ok=True)
    MIRRORS.write_text(wanted)
    print(f"wrote {MIRRORS} ({wanted.count('#[frb(mirror(')} types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
