#!/usr/bin/env bash
# Z Privacy for Linux, assembled by a script instead of by hand.
#
#     bash scripts/package_linux.sh
#
# The archive on beta was put together by hand on 30 September and never rebuilt,
# so what people have been downloading predates the PDF reader, the names, the
# language packs and the gateway. This script is how that stops being possible:
# the layout is in code, the build is from a clean tree, and the archive names
# the commit it came from.
#
# It writes two files and touches nothing else:
#
#     dist/zprivacy-v1-linux-x86_64.tar.gz
#     dist/zprivacy-v1-linux-x86_64.tar.gz.sha256
#
# A dirty tree is refused, because an archive whose contents are not in a commit
# cannot be rebuilt by anybody. `ALLOW_DIRTY=1` overrides it, and then BUILD-INFO
# says so in as many words.
set -uo pipefail
cd "$(dirname "$0")/.." || exit 2
ROOT="$PWD"
NAME="zprivacy-v1-linux-x86_64"
OUT="$ROOT/dist"
STAGE="$OUT/$NAME"

step() { printf '\n== %s\n' "$1"; }
die() { printf '\n%s\n' "$1" >&2; exit 1; }

# ---------------------------------------------------------------- the tree
DIRTY=""
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  if [ "${ALLOW_DIRTY:-}" = "1" ]; then
    DIRTY="yes"
  else
    git status --short | head -20
    die "the tree is not clean. Commit, or set ALLOW_DIRTY=1 and the archive will say so."
  fi
fi
COMMIT=$(git rev-parse HEAD 2>/dev/null || echo unknown)
SUBJECT=$(git log -1 --format=%s 2>/dev/null || echo unknown)

step "building (release)"
( cd apps/flutter_app && flutter build linux --release ) || die "the Flutter build failed"
BUNDLE="$ROOT/apps/flutter_app/build/linux/x64/release/bundle"
[ -x "$BUNDLE/zprivacy" ] || die "no runner at $BUNDLE/zprivacy"

# The core's own stamp, read out of a binary built from this tree — the same
# line the window shows and the copied report carries.
STAMP=$(cargo run -q --release -p z_core --example check_document 2>/dev/null | head -1)
[ -n "$STAMP" ] || die "the core would not say its own stamp"

step "assembling $NAME"
rm -rf "$STAGE"
mkdir -p "$STAGE"
cp -a "$BUNDLE/." "$STAGE/"

# The mark, for whoever wants a launcher.
mkdir -p "$STAGE/icons"
for size in 16 32 48 64 128 256 512; do
  src="$ROOT/apps/flutter_app/assets/brand/zprivacy-${size}.png"
  [ -f "$src" ] && cp -f "$src" "$STAGE/icons/zprivacy-${size}.png"
done
cp -f "$ROOT/packaging/linux/zprivacy.desktop" "$STAGE/zprivacy.desktop"
cp -f "$ROOT/packaging/linux/install-shortcut.sh" "$STAGE/install-shortcut.sh"
chmod +x "$STAGE/install-shortcut.sh"

cp -f "$ROOT/LICENSE" "$STAGE/LICENSE" 2>/dev/null || die "no LICENSE at the root"
cp -f "$ROOT/packaging/linux/README.txt" "$STAGE/README.txt" || die "no packaging/linux/README.txt"

# ---------------------------------------------------------------- third party
mkdir -p "$STAGE/third-party"
cp -f "$ROOT/site/third-party/flutter-engine-LICENSE.txt" "$STAGE/third-party/" 2>/dev/null
for f in NOTICES.txt flutter-sdk-LICENSE.txt material-icons-LICENSE.txt \
         dejavu-LICENSE.txt dart-pdf-LICENSE.txt; do
  [ -f "$ROOT/packaging/linux/third-party/$f" ] && cp -f "$ROOT/packaging/linux/third-party/$f" "$STAGE/third-party/"
done
# Generated, not copied from September: the crates are whatever this tree
# actually depends on today.
{
  echo "The Rust crates this build links, from the tree at $COMMIT."
  echo "Generated by scripts/package_linux.sh with cargo tree; no new tool."
  echo
  ( cd "$ROOT" && cargo tree -p z_core --edges normal --prefix none 2>/dev/null \
      | sed 's/ (\*)$//' | sort -u | grep -vE '^$' )
} > "$STAGE/third-party/rust-crates.txt"

# ---------------------------------------------------------------- build info
RUNNER_SHA=$(sha256sum "$STAGE/zprivacy" | cut -d' ' -f1)
BRIDGE_SHA=$(sha256sum "$STAGE/lib/libz_bridge.so" | cut -d' ' -f1)
{
  echo "Z Privacy V1 — release build"
  echo "============================"
  echo
  echo "core stamp       $STAMP"
  echo "product commit   $COMMIT"
  echo "                   \"$SUBJECT\""
  if [ -n "$DIRTY" ]; then
    echo "                 BUILT FROM A TREE THAT WAS NOT CLEAN (ALLOW_DIRTY=1)."
    echo "                 What is in this archive is not exactly what is in that"
    echo "                 commit, and cannot be rebuilt from it."
  else
    echo "                 The tree was clean when these binaries were built."
  fi
  echo
  echo "built            $(date -Iseconds), $(uname -s) $(uname -m)"
  echo "rustc            $(rustc --version 2>/dev/null)"
  echo "flutter          $(cd apps/flutter_app && flutter --version 2>/dev/null | head -1)"
  echo "profile          release, assembled by scripts/package_linux.sh"
  echo
  echo "the two files that are the product"
  echo "  zprivacy            $RUNNER_SHA"
  echo "  lib/libz_bridge.so  $BRIDGE_SHA"
  echo
  echo "These two hashes are the ones to check. The hash of the archive itself"
  echo "cannot be inside the archive: it travels beside it, in"
  echo "$NAME.tar.gz.sha256, and is printed on the download page."
  echo
  echo "  sha256sum -c $NAME.tar.gz.sha256"
} > "$STAGE/BUILD-INFO.txt"

# ---------------------------------------------------------------- the archive
step "writing the archive"
( cd "$OUT" && tar czf "$NAME.tar.gz" "$NAME" ) || die "tar failed"
( cd "$OUT" && sha256sum "$NAME.tar.gz" > "$NAME.tar.gz.sha256" )
rm -rf "$STAGE"

ARCHIVE_SHA=$(cut -d' ' -f1 < "$OUT/$NAME.tar.gz.sha256")
SIZE=$(du -h "$OUT/$NAME.tar.gz" | cut -f1)

printf '\n%s\n' "done"
printf '  %s\n' "$STAMP"
printf '  archive  dist/%s  (%s)\n' "$NAME.tar.gz" "$SIZE"
printf '  sha256   %s\n' "$ARCHIVE_SHA"
[ -n "$DIRTY" ] && printf '  note     built from a tree that was not clean\n'
exit 0
